### ISSUE TITLE
Auto-update error

### ISSUE THREAD

**Issue by wardav** [ThePacielloGroup/CCAe#100]
Whenever I use CCA on Windows 64bit, I got an auto-update error that the 1.1.0. version has not been signed.

![image](https://user-images.githubusercontent.com/38493807/55712941-95612580-59e7-11e9-82f4-1d42989d3760.png)

**Comment by ferllings** [comment]
MSI or EXE installer?

**Comment by ferllings** [comment]
Maybe related to https://github.com/electron-userland/electron-builder/issues/3667
