### ISSUE TITLE
HSV slider

### ISSUE THREAD

**Issue by mlamond** [ThePacielloGroup/CCAe#103]
**Is your feature request related to a problem? Please describe.**
The previous version had an HSV slider that allowed you to change the color within the Analyzer tool. If a color didn't pass contrast requirements, you could easily use the slider to get it to where it would pass. This was something I used frequently. 

**Describe the solution you'd like**
I'd like to see the HSV slider added back in.

**Comment by patrickhlauke** [comment]
note that while we don't have HSV sliders, we do have HSL (mainly because CSS supports `hsl(...)` / `hsla(...)`, and there's no direct equivalent for HSV)

> ![CCA with HSL sliders open](https://user-images.githubusercontent.com/895831/55923899-98cef980-5bff-11e9-9c30-f52890d2c77b.PNG)
