### ISSUE TITLE
Change to layout so application window does not extend beyond view

### ISSUE THREAD

**Issue by mlamond** [ThePacielloGroup/CCAe#109]
**Is your feature request related to a problem? Please describe.**
When sliders are displayed and accordions are expanded, analyzer window extends beyond view.

**Describe the solution you'd like**
Prefer a landscape layout, or at least ability to resize window.

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/43453361/56315183-0fe71f00-6125-11e9-9c14-3f9230034977.png)

**Comment by Buckaroo253** [comment]
Bump

**Comment by ferllings** [comment]
I've not forgotten, but I have difficulties to find a correct solution.

The current idea would be move to a 2 columns layout.
<img width="834" alt="Screen Shot 2019-10-11 at 11 23 35 AM" src="https://user-images.githubusercontent.com/2118130/67752389-33274b00-fa33-11e9-97db-8f6dd6df6259.png">

But it would introduce scrollbars, which I'm trying to avoid.

**Comment by mlamond** [comment]
Thank you for working on this! I think the two-column approach is the right direction. 

I know what you have there is just a quick wireframe, but one thing I would add and emphasize is the contrast ratio and the pass/fail status. In the current implementation and your wireframes, more real estate is being given to the description of the guidelines (within the accordion, I'm assuming that's what the lorem ipsem is meant to be?)

The contrast ratio and pass/fail is THE MOST important piece of information. It's what I specifically use the tool for (that, and the screen simulation option, which I hope will remain available.) It should be recognizable and obvious at a glance.

I know I sound like one of those people who don't like change, but my advice would be to look back to the previous version and refine that. There wasn't much I could find wrong with this version. But the look and feel could be refined. Usability was already on point. Very intuitive tool:
![image](https://user-images.githubusercontent.com/43453361/67776839-49cfa100-fa37-11e9-88ab-a7b53becc9f2.png)

**Comment by Buckaroo253** [comment]
Why are you trying to avoid scrollbars?

**Comment by ferllings** [comment]
I'm closing this issue to group all design improvements on ticket #113
