### ISSUE TITLE
Auto Update error

### ISSUE THREAD

**Issue by cjromano99** [ThePacielloGroup/CCAe#116]
When launching CCA, Version (1.0), users are getting the same error listed in this post:

https://github.com/ThePacielloGroup/CCAe/issues/100

It appears CCA is trying to download and install an update.
This is on a Windows 10 v1703.  I installed using the CCA-Setup-1.0.0.exe

I've seen other users list this error but did not see a resolution.  Let me know if you need additional information.

**Comment by ferllings** [comment]
The fix will be available with the next build

**Comment by cjromano99** [comment]
Thanks!  Is there a timeframe for the next build?
