### ISSUE TITLE
A JavaScript error occurred in the main process - updateDeficiencyForeground is not a function

### ISSUE THREAD

**Issue by svenkapudija** [ThePacielloGroup/CCAe#117]
**Describe the bug**
When clicked on the button to, I guess, switch/reverse the colors - the error pops out and nothing happens after error pop-up is closed.

**Desktop:**
 - OS: Mac OS X El Capitan
 - Version 10.11.3

**To Reproduce**
Open analyzer, click on the button with two arrows pointing up/down.

**Expected behavior**
I guess reverse the colors?

**Screenshots**
![Screen_Shot_2019-05-14_at_14_49_07](https://user-images.githubusercontent.com/552692/57699294-b9073380-7657-11e9-91e6-58c9e0db4307.jpg)
![08](https://user-images.githubusercontent.com/552692/57699312-c02e4180-7657-11e9-98da-d0bcec7dce81.jpg)

**Comment by ferllings** [comment]
Fixed on 6f513fa7a2fc65b7705b8474f7d7603ab15328f6 (but not released yet)
