### ISSUE TITLE
Foreground/Background Switcher

### ISSUE THREAD

**Issue by claytoncarney** [ThePacielloGroup/CCAe#118]
**Describe the bug**
Error encountered using Foreground/Background Switcher

**Desktop**
Windows 10 64-bit
Version 1803

**To Reproduce**
Click the button:

![cca2](https://user-images.githubusercontent.com/1275536/58224927-eb123880-7cdc-11e9-91b6-4c21640dbeb9.png)

**Expected behavior**
Swap foreground/background colors.

**Actual Behavior**

![cca](https://user-images.githubusercontent.com/1275536/58224813-645d5b80-7cdc-11e9-9e40-c3e85cb4243b.png)

**Comment by ferllings** [comment]
Fixed in 6f513fa7a2fc65b7705b8474f7d7603ab15328f6
