### ISSUE TITLE
No autoupdate

### ISSUE THREAD

**Issue by iadawn** [ThePacielloGroup/CCAe#123]
**Is your feature request related to a problem? Please describe.**

We cannot have autoupdating applications deployed to our corporate network. This presents an unacceptable security risk for our organisation.

**Describe the solution you'd like**

Provide a build that only supports manual updates.

Thanks :)

**Comment by ferllings** [comment]
Yes, it's already planned.

**Comment by iadawn** [comment]
Hate to be pushy, but any idea on timeline? Even roughly :)

**Comment by ferllings** [comment]
Sorry, no timeline. I'm working on my free time.
