### ISSUE TITLE
Contrast Ratio Precision

### ISSUE THREAD

**Issue by claytoncarney** [ThePacielloGroup/CCAe#124]
**Describe the bug**
Preferences > Options > Contrast ratio precision no longer works. Regardless of selection, precision is always 1 decimal place.

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bits
 - Version 1.1.2

**To Reproduce**
Select precision at 2 decimal places

**Expected behavior**
2 decimal places are displayed

**Screenshots**
![cca](https://user-images.githubusercontent.com/1275536/59803186-fb9bdb80-92a7-11e9-8b8e-7f10129adddc.png)

**Additional context**

**Comment by ferllings** [comment]
So if you save, and select another color, the precision stays at 1 decimal?

**Comment by claytoncarney** [comment]
Very odd. After clicking save, it is displaying 2 decimal places. I had
never changed the setting; it was always at 2 decimal places. It was after
updating to 1.1.2 that this issue was observed. I had use CCA several days
after the update, and the behavior was consistent: 1 decimal place. Now,
after clicking save (even though I did not change the setting), I can not
reproduce the issue. In fact, after clicking save, it immediately began
displaying 2 decimal places; no need to select another color. But without
clicking save, it was always displaying 1 decimal place.

**Comment by patrickhlauke** [comment]
i'll guess that in the previous version, this setting didn't even exist, and as you updated, it didn't then set a new default of 2...so in essence it had no actual preference set, and/or then defaulted to 1 digit somehow...

**Comment by claytoncarney** [comment]
I checked version 1.1.1 and it did have the setting. I should mention that I am using the portable version. I don't have the time to reverse engineer the code to figure out where config info is stored and clear it. Perhaps there was a change in config info format between versions?
