### ISSUE TITLE
Windows 10 blocking installation

### ISSUE THREAD

**Issue by jcoschi** [ThePacielloGroup/CCAe#125]
**Describe the bug**
Windows blocks installation with the **CCA-Setup.1.1.2.exe**.

**Desktop (please complete the following information):**
 - OS:  Windows 10 64bit
 - Version 1.1.2

**To Reproduce**
Download [CCA-Setup-1.1.2.exe](https://github.com/ThePacielloGroup/CCAe/releases/tag/v1.1.2) and execute file.

**Expected behavior**
I would expect this installer to have a valid publisher.

**Screenshots**
![cca](https://user-images.githubusercontent.com/9099866/59929419-c8279100-940e-11e9-9bc8-8fdad34db4d9.png)

**Comment by ferllings** [comment]
Thanks. This is a problem with the certificate. We need to buy a new one.

**Comment by RRC-TX-IS** [comment]
When will the new certificate be purchased?
Thanks for your time

**Comment by pgorelik25** [comment]
I would also like to know when the certificate will be purchased so it can be installed on Windows 10. Thank you.
