### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by davidofyork** [ThePacielloGroup/CCAe#132]
**Describe the bug**
When selecting colors using the color picker, I frequently encounter the following issue. 

![Screenshot 2019-09-30 at 10 52 02](https://user-images.githubusercontent.com/8956488/65873735-c4939680-e37b-11e9-953e-675914dd7dfb.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Version: 10.14.6

Difficult to reproduce consistently, but occurs when selecting a color.

**Comment by ferllings** [comment]
Can't reproduce. Probably fixed with the new native picker
