### ISSUE TITLE
Zoom at Magnifier (Color Picker)

### ISSUE THREAD

**Issue by OLLI-S** [ThePacielloGroup/CCAe#134]
**Is your feature request related to a problem? Please describe.**
With the new version of the CCA selecting the correct pixel is nearly impossible, because there is no zoom (magnifier) at the color picker mouse cursor.

**Describe the solution you'd like**
Please implement a zoom (magnifier) at the color picker (like you had it in CCA 2.1.
This makes the selection of the correct pixel much easier.

**Comment by ferllings** [comment]
Duplicate of #122
