### ISSUE TITLE
Consider adapting Version-Numer

### ISSUE THREAD

**Issue by OLLI-S** [ThePacielloGroup/CCAe#136]
**Is your feature request related to a problem? Please describe.**
The **old** CCA had version **2.x**, the **new** version is **1.x**.
This is totally confusing, that a new version has a lower version number (**although the name of the tool is not changed**). A programmer asked me where to get the new CCA 2.x (that I am using) because he found only 1.x (an older version).

**Describe the solution you'd like**
Please consider increasing the version number to **3.x** to avoid confusion about the version number.

**Comment by ferllings** [comment]
Same request came by email:
"J’ai bien compris que cette nouvelle version de Colour Contrast Analyser avait été complètement redéveloppée à l’aide d’Electron.
Pour autant, je trouve déroutant que la nouvelle version s’appelle 1.2.1 alors que l’ancienne version Windows s’appelait 2.5.0 et l’ancienne version Mac s’appelait 2.4. Beaucoup d’autres utilisateurs  risquent également d’être déroutés."

I'm considering to directly jump to 3.x

**Comment by patrickhlauke** [comment]
agree, seems the most sensible jump at this stage (also, switching to the new color picker mechanism itself can probably be considered a big enough jump/break with the past for this not to be too much against semver, despite skipping a whole version number)
