### ISSUE TITLE
Multi-Language support

### ISSUE THREAD

**Issue by OLLI-S** [ThePacielloGroup/CCAe#137]
**Is your feature request related to a problem? Please describe.**
Currently CCA is available in English language only.
For some colleagues this is a pain, because their English skills are very bad.

**Describe the solution you'd like**
Please consider adding multiple languages in CCA where users can select from.
**I offer my help in translating CCA into German language** if this is needed.

**Comment by ferllings** [comment]
Thanks @OLLI-S, The i18n support has been added on the latest commits but not packaged yet.
If you can provide a translated version of this file https://github.com/ThePacielloGroup/CCAe/blob/master/src/views/translations/en.json that would be great !

**Comment by OLLI-S** [comment]
The translation could take several days/weeks because I do this in my free time.

I am new to GH, so how do I provide my translated file?
Should I download the en.json and translate it offline?
And how do I upload it?
Or is there a way that I translate it directly in the web browser?

About the file format:
I assume that the first value is the identifier and the second value should be translated?
> "Edit": "Edit",

**Comment by ferllings** [comment]
I understand, I'm doing it on my free time as well.

Just download the file and you can re-upload it on this ticket. I'll take care of the rest.
And yes, only the 2nd value should be translated.

**Comment by OLLI-S** [comment]
OK, cool, starting working on it today

**Comment by MakotoUeki** [comment]
@ferllings Could I do Japanese translation as well?

**Comment by ferllings** [comment]
Thanks, but the Japanese translation has already been done by @motchie.
So far I have Japanese and French

**Comment by MakotoUeki** [comment]
Great! That's good to know. I'm looking forward to the update version :-)

**Comment by OLLI-S** [comment]
Do you plan to release the names of the translators in the app?

**Comment by ferllings** [comment]
Yes, I can put full names or github usernames, in the About dialog

**Comment by OLLI-S** [comment]
I am finished with the translation, but I have some annotations:

1) German text is mostly longer than English text (so it won't fit in the components)

2) I did not translate main knots (like "Menu" or "Main") and the name of the aplication (lines 3, 29, 120)

3) I did translate Titles (lines 81, 105 and 119)

4) I did not find the colour-names that you show in the right-top corner of the foreground-colour/background-colour and also in the help for the foreground/background colour

5) In the file I see two spellings for colour (colour and color), this should be unique

6) What is the context of line 9?
Is it a dialog title or a message that the updates are installed (installing updates)?

7) The buttons have no tooltip info (but you have the texts in the language file)

8) I have no proper translateion for "Paraphrased" (line 75)
So I translated it with "Erklärung" what means "explanation"

9) In line 78 there is no "." at the end of the sentence, so I added it in my translation (you should also add it in the Englisch text).

10) I did not translate "TPG Resources" in line 124 because this is the name of the website.
Tell me if I should translate it.

11) In the OLD version of the CCA words like "Protanopia" were translated with the explanation "Red Blindness").
In the current version you have "no red", so I decided not to translate "Protanopia" and all the other medical words.
Tell me if I should translate it.

If you want to publish my name, please use "Oliver Sahr"    

Here is the translated file (that I had to rename to *.TXT, otherwise an upload was not possible).
[de.json.txt](https://github.com/ThePacielloGroup/CCAe/files/3747808/de.json.txt)

**Comment by ferllings** [comment]
Sorry for the delay, I was afk.

1. I don't want to delay this release any longer so I'll push it  as it is. But I'm working on a redesign to fix #109 so I'll think about it at the same time.

4. The colors are CSS names, so I don't think it's necessary to translate them.

5. Good point. It should be Colour.

6. A menu item, in the main navigation menu.

7. Yes, that's the textual alternative for screenreaders. 

10. No need to.

Thanks for your contribution.

I'll create a section in the About to list the translators. Could let me know how to translate the word "Translations"?

**Comment by ferllings** [comment]
@motchie, similarly, how do you translate "Translations" and "Japanese"... in Japanese?

**Comment by motchie** [comment]
@ferllings I'm sorry for late reply. "Translations" (the act of changing from one language to another) is `翻訳` and "Japanese" (the language used in Japan) is `日本語` in Japanese.

**Comment by OLLI-S** [comment]
> 4. A menu item, in the main navigation menu.
> 5. Yes, that's the textual alternative for screenreaders.
> 6. No need to.

What of my topics does you answers refer to?

> Could let me know how to translate the word "Translations"?

Translations in German means "Übersetzungen".
