### ISSUE TITLE
Mac version crashes often

### ISSUE THREAD

**Issue by sprungmarker** [ThePacielloGroup/CCAe#140]
**Describe the bug**
Mac version crashes often, if you use the color picker.

**Desktop (please complete the following information):**
 - Mac OS
 - 1.2.0

**To Reproduce**
Open app, use one of the two color picker, app crashes nearly on every occasion.

**Comment by igotabeme** [comment]
Having the exact same issue. I deleted the app and tried to reinstall and now it's telling me I can't install and need to contact the developers.

**Comment by ferllings** [comment]
Fixed in v1.2.1
