### ISSUE TITLE
Install issues continue on OS Catalina

### ISSUE THREAD

**Issue by igotabeme** [ThePacielloGroup/CCAe#143]
**Describe the bug**
Like the 1.2.0 version, I can not install the updated 1.2.1 version. 

**Desktop (please complete the following information):**
 - OS: Catalina
 - Version 10.15.1

**To Reproduce**
1) Downloaded CCA-1.2.1.dmg/opened install file, dragged to applications/went to applications folder to open app/ receive error message
![image](https://user-images.githubusercontent.com/51974570/68768205-145ab400-05f0-11ea-8f26-57674fd8040e.png)

2) Downloaded CCA-1.2.1.zip/immediately received this download error:
![image](https://user-images.githubusercontent.com/51974570/68768273-3c4a1780-05f0-11ea-91c6-6af4dc0705ce.png)

3) Told the computer to proceed with the zip download/unzipped/attempted to launch install/received this error:
![image](https://user-images.githubusercontent.com/51974570/68768375-64397b00-05f0-11ea-91b5-db3478d6e3c9.png)

**Expected behavior**
Expected the app to open for use.

**Screenshots**
Please see above.

**Additional context**

**Comment by ferllings** [comment]
Looks like it's related to this issue https://github.com/electron-userland/electron-builder/issues/4179

**Comment by patrickhlauke** [comment]
https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution

**Comment by ferllings** [comment]
Fixed with commit 12ea9db72513e64cff1f74ae72a4ff6ca60b7067
