### ISSUE TITLE
Small typo in German GUI

### ISSUE THREAD

**Issue by reneandritsch** [ThePacielloGroup/CCAe#146]
**Describe the bug**
In the lower area there are two small typos in the UI.

**Desktop (please complete the following information):**
 - Mac OS 10.14.6

**Expected behavior**
Instead of “Notmaler” it should read “Normaler” see screenshot

![German_typos](https://user-images.githubusercontent.com/38455050/74043721-2fa84600-49ca-11ea-9511-136ab96f1be5.png)

**Comment by patrickhlauke** [comment]
closed by https://github.com/ThePacielloGroup/CCAe/pull/144
