### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by catmelbis** [ThePacielloGroup/CCAe#147]
**Describe the bug**
Hi, Since I have install Catalina, The colour picker doesn't «read» the colour underneath...
It shows this error message: 

<img width="424" alt="Capture d’écran, le 2020-02-10 à 16 40 15" src="https://user-images.githubusercontent.com/60901302/74193207-f6b7dd80-4c24-11ea-960e-5f6929a11e2d.png">
**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Version : 10.15.2

**To Reproduce**
1_Open the app.
2-Take the colour picker 
3-move the colour picker around in the screen...and the colour just don't match what is underneath 

**Expected behavior**
Normally, the colour picker shows the right colour

**Screenshots**
<img width="1680" alt="Capture d’écran, le 2020-02-10 à 16 53 09" src="https://user-images.githubusercontent.com/60901302/74193736-e6543280-4c25-11ea-9009-726cc7d2ef5b.png">

**Additional context**

**Comment by ferllings** [comment]
This should be fixed in the next release, as the Javascript picker will be replaced with native compiled versions.

**Comment by ferllings** [comment]
Fixed in 3addd33224e7ea0ca3626581a946232fcdaf6dec
