### ISSUE TITLE
Rename "Advanced results" to, perhaps, "Verbose results", and make it a text box which auto-selects all and/or has a copy button

### ISSUE THREAD

**Issue by patrickhlauke** [ThePacielloGroup/CCAe#15]

**Comment by ferllings** [comment]
The reason for not using textarea was to be able to style parts of the text (bold, italic). 
I believe this all section need to be re-designed

**Comment by patrickhlauke** [comment]
wondering if, just for the title of the section, something verbose like "Results summary (in text)" would make sense

**Comment by ferllings** [comment]
Removed in new layout
