### ISSUE TITLE
Where can I find the infrastructure requirements for CCAe?

### ISSUE THREAD

**Issue by rosanw** [ThePacielloGroup/CCAe#152]
I am trying to find the infrastructure requirements for installing/running CCAe. I was also wondering where data is stored. Can you point me in the direction of where I can find this information?

**Comment by ferllings** [comment]
The requirements are based on Electronjs:
https://www.electronjs.org/docs/tutorial/support#supported-platforms

The data can be found here:
MacOS: ~/Library/Application Support/cca
Windows: C:\Users\<user>\AppData\cca

**Comment by rosanw** [comment]
Thank you. Do you have any information about RAM and CPU requirements?

**Comment by ferllings** [comment]
It's based on Chromium so probably the same requirements
