### ISSUE TITLE
HSL/HSV sliders corrupt HEX colour values

### ISSUE THREAD

**Issue by EricDunsworth** [ThePacielloGroup/CCAe#155]
I've noticed that in v3.0.0 (not sure about older versions), the HSL lightness and HSV value sliders corrupt HEX foreground/background colour values.

**How to reproduce:**

1. Open CCAe.
2. Ensure the foreground colour type is set to HEX and that its value is ``#000000``.
3. Press the slider button at the bottom of the foreground colour panel (it's in-between the arrows/droplet buttons).
4. Press the HSL button.
5. Change the lightness slider's value to anything between 1 and 99.

**Expected outcome:**
Foreground colour changes to a tone of grey with a 6 character HEX value (e.g. ``#EEEEEE``).

**Actual outcome:**
Foreground colour's HEX value gets corrupted. For example:
* Lightness: 1 changes the HEX value to ``#2.999999999999A2.999999999999A2.999999999999A``
* Lightness: 99 changes the HEX value to ``#FC.666666666668FC.666666666668FC.666666666668``

**Note:**
HEX colours don't get corrupted if the lightness slider is set to 0 (``#000000``) or to 100 (``#FFFFFF``).

**Comment by ferllings** [comment]
Fixed in #154
