### ISSUE TITLE
Color picker not usable when using external monitor

### ISSUE THREAD

**Issue by weboverhauls** [ThePacielloGroup/CCAe#157]
Color picker not usable when using external monitor.

**Desktop (please complete the following information):**
 OSX 10.15.3

**To Reproduce**
Use the color picker.

**Expected behavior**
Picks color that the picker tool is pointing to.

In screen shot, picker should be picking white but is not.

![image](https://user-images.githubusercontent.com/473400/77179144-73e53680-6a9e-11ea-8c60-89a5d790dad4.png)

**Comment by ferllings** [comment]
There might be something else involved: It works for me and I use the same OSX version, with an external monitor.

**Comment by weboverhauls** [comment]
Someone else said restarting computer fixed it. But didn't work for me. 🤷‍♂️

**Comment by ferllings** [comment]
I'll ask around and see if someone else has the same issue

**Comment by patrickhlauke** [comment]
different pixel density perhaps? i.e. retina display and regular non-retina external monitor? or vice-versa?

**Comment by mfairchild365** [comment]
This just fixed it for me: System preferences > security & privacy > privacy > screen recording > check CCA if it is not already checked.

Does that help?

**Comment by poorgeek** [comment]
In Settings, under Security & Privacy > Privacy tab, make sure that the Screen Recording permissions are enabled for CCA. I can toggle that permission and get the same results as the issue.

**Comment by weboverhauls** [comment]
That fixed it, thank you!
