### ISSUE TITLE
Hover Colour not working

### ISSUE THREAD

**Issue by Lordzytech** [ThePacielloGroup/CCAe#159]
Hi everyone, in the old CCA you used to be able to access the hover state colour of a menu on a website, this version does not allow this.

Is there a chance we could have a quick update as we use this for website accessibility thank you.

![Annotation 2020-03-23 154226](https://user-images.githubusercontent.com/13315298/77334614-f5e29300-6d1c-11ea-99fc-958be0c5ee01.png)

**Comment by ferllings** [comment]
This is not the desired behavior: the color picker should not change the of the element currently targeted.
You should use the browser dev. tools to force the hover style.
