### ISSUE TITLE
Failure to launch

### ISSUE THREAD

**Issue by mrLOUDY** [ThePacielloGroup/CCAe#160]
<img width="737" alt="Screen Shot 2020-03-24 at 10 09 46 PM" src="https://user-images.githubusercontent.com/62636277/77504656-32e27e80-6e1e-11ea-8efc-0a9bc5de3b73.png">
**Describe the bug**
Can not launch application after install

**Desktop (please complete the following information):**
 - OS: Mac OS 
 - Version Catalina 10.15.3

**To Reproduce**
Steps to reproduce the behavior: Launch app after install

**Expected behavior**
For the application to run

**Screenshots**
see attached

**Additional context**

**Comment by ferllings** [comment]
You need to allow apps from identified developers (the app is signed)

System Preferences > Security & Privacy > General

at the bottom "Allow apps downloaded from:" "App Store and identified developers"

**Comment by jcbriones** [comment]
Same issue in #143

**Comment by mrLOUDY** [comment]
Thanks for the assist. It's up and running!
