### ISSUE TITLE
CCA Window resizes after minimizing - portion of content truncated

### ISSUE THREAD

**Issue by deconspray** [ThePacielloGroup/CCAe#161]
**Describe the bug**
After using CCA to analyze colours, the CCA window is manually minimized. When the window is later restored, a portion of the CCA's content is truncated, without any way to scroll down to view the content.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro

**To Reproduce**
* Open CCA
* Perform a colour analysis.
* Minimize the CCA window
* Restore the CCA window

**Expected behavior**
Window sized the same, all content accessible.

**Screenshots**
Default CCA dialog window
![Default CCA dialog window](https://user-images.githubusercontent.com/1461525/77925095-11442580-726a-11ea-96e7-f1f70900355e.png)

CCA dialog window after minimizing/restore, with truncated content, no vertical scroll bars
![CCA dialog window after minimizing/restore, with truncated content, no vertical scroll bars](https://user-images.githubusercontent.com/1461525/77925223-3a64b600-726a-11ea-9fa7-8bc3a7e03565.png)

**Additional context**

**Comment by ferllings** [comment]
On my latest tests this problem seems to be gone.
Please re-open if not
