### ISSUE TITLE
User guidance - pixel selection

### ISSUE THREAD

**Issue by mnciao** [ThePacielloGroup/CCAe#165]
The new CCA looks really cool - particularly love the ability to select the exact pixel. Can you provide guidance for users on how to determine which pixel (or sets of pixels) in a text or background to select for consistent, reliable evaluation? 
Thanks

**Comment by ferllings** [comment]
Thanks, we are trying to make it the more efficient as we can.
Before using the color picker, if you have access to the code, I would try to look for the exact color value in hex, rgb etc..
This is by far the most trusted way to get a reliable.
The color picker basically read the pixel value after it as been processed by all the rendering process.
Which means the captured value may be different depending of your color profile and browsers. (we are still trying to find a way to compensate that)

Finding the right pixel to capture is also sometimes complex, if your font is small antialiased, if the text background is an image.
At the end it is up to the tester judgement to find the most representative pixel (color) of your element, within a set.
You should also try different combinations. And if some of them are failing, maybe the all element contrast should be increased.

Hope it helps.

**Comment by mnciao** [comment]
Thank you for taking the time to provide the feedback.
We do advise folks to enlarge the view in order to effectively place the picker.
And, as you note, if the font is small, there are inherent issues with clarity, so that may well be a warning flag in addition to the color.
One concern is it would be nice, absent the code, to have a method to determine whether a text fails if some selections fail while others don’t.
Best,
Jay
