### ISSUE TITLE
Can't be opened because Apple cannot check it for malicious software

### ISSUE THREAD

**Issue by Brynman** [ThePacielloGroup/CCAe#166]
**Describe the bug**
As the screen shot suggests I am not open the application after installing it.

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Version 10.15.4 Beta (19E258a)

**To Reproduce**
Steps to reproduce the behavior: download https://github.com/ThePacielloGroup/CCAe/releases/download/v3.0.1/CCA-3.0.1.dmg

**Expected behavior**
I would expect the application to open

**Screenshots**
![image](https://user-images.githubusercontent.com/60389544/79594748-879faf00-80d5-11ea-97b3-86d9db475bd4.png)

**Additional context**
NA

**Comment by SuzLM** [comment]
I have the same issue.
OS: Catalina 10.15.3

**Comment by ferllings** [comment]
You need to allow apps from identified developers (the app is signed)

System Preferences > Security & Privacy > General

at the bottom "Allow apps downloaded from:" "App Store and identified developers"

**Comment by patrickhlauke** [comment]
we should consider documenting these contortions somewhere...possibly in the readme here?

**Comment by SuzLM** [comment]
Thank you. that worked.

**Comment by Brynman** [comment]
Checked my settings which were already set to allow "App Store and identified developers" but still not working for me I am afraid...
![image](https://user-images.githubusercontent.com/60389544/79864827-05173800-83d2-11ea-8c8f-e8f852961492.png)

**Comment by kurtcalloway** [comment]
I'm experiencing the same issue as Brynman; I can't open it either on my Mac (macOS Catalina 10.15.4) and have my Security & Privacy set to allow app downloads from App Store and identified developers. My Mac can't check it for malicious software.

**Comment by udacityanna** [comment]
I am also experiencing this on Catalina.
<img width="463" alt="message in settings" src="https://user-images.githubusercontent.com/12027531/80762130-e9b2d800-8b09-11ea-96a5-668cdba8bca0.png">

**Comment by hallmedia** [comment]
Same as last few commenters. “App Store and identified developers.” is the selection. Running macOS 10.15.4 on brand new MacBookAir. Still seeing “Colour Contrast Analyser (CCA)” can’t be opened because Apple cannot check it for malicious software.”

**Comment by emes001** [comment]
Came here to say the same. I was able to open it by going into Security & Privacy and using "Open Anyway". Using macOS 10.15.4 as well.

**Comment by ferllings** [comment]
Thanks for all your comments.
I'm trying to understand why the application is flagged despite it's signed with an Apple dev certificate.
