### ISSUE TITLE
Picker not aligned with mouse pointer on high-dpi /scaled display (windows)

### ISSUE THREAD

**Issue by patrickhlauke** [ThePacielloGroup/CCAe#17]
noticed on Surface 2 (which by default is set to a 150% scaling factor)

![photo 03-08-2018 16 17 12](https://user-images.githubusercontent.com/895831/43651067-469b9b5e-9739-11e8-9222-acd67416611d.jpg)

<img width="683" alt="capture" src="https://user-images.githubusercontent.com/895831/43651315-ef6692b6-9739-11e8-928f-c23ae6f1a204.PNG">

strangely, setting scaling to 100% (which makes it extremely tiny to work with on the laptop), instead of the preview circle thing the cursor just turns to a cross.

![photo 03-08-2018 16 23 46](https://user-images.githubusercontent.com/895831/43651303-e589e89c-9739-11e8-97e5-9b6b28afddd6.jpg)

**Comment by ferllings** [comment]
Can replicate on VM.

Possibly related https://github.com/octalmage/robotjs/issues/400

**Comment by patrickhlauke** [comment]
not knowing anything about how to build this stuff, but from my webdev: can you test for `window.devicePixelRatio` and divide or multiply by that?

**Comment by patrickhlauke** [comment]
(e.g. on the Surface Pro 2017, with its 200% scale, it reports `2`. on the old surface 2, it reports `1.5`)
