### ISSUE TITLE
Optional hash in colour code field

### ISSUE THREAD

**Issue by cpshanley** [ThePacielloGroup/CCAe#171]
The FG and BG fields require a has to be present at the start. This can be inconvenient, especially when pasting a hex code that has no hash.

It would be good if CCA could look at the content of the field on change. If there is a hash symbol, take no action. If there is no hash symbol, infer it.

Would make life easier. Cheers, and keep up the good work!

**Comment by ferllings** [comment]
Hi @cpshanley, could you develop an example? I don't understand why the hash symbol is a problem on copy/paste.

**Comment by cpshanley** [comment]
Sure.

Let's say you are using Sketch (or whatever) and have copied a colour hex code, but that code does not include the hash. So it copies 84D7B7 instead of #84D7B7.

Now click in the FG field of CCA. When you click in the field the entire current contents is selected. So you paste in 84D7B7 to replace it. But CCA does not recognise that as a valid hex code because there is no hash symbol and an exclamation mark is displayed in the field. The only way to correct it is to manually add a hash symbol after you have pasted the code.

Does that make sense? Cheers.

**Comment by ferllings** [comment]
I see now. Thanks.
I'll have to look at the regexp for the hex format, but I believe it's possible to either validate without hash, or automatically add the hash. I'll see what works best.

**Comment by cpshanley** [comment]
I'm no developer, but CCA must check some sort of onChange event (that's is how it gets the colour value). So if there is a hash, fine. But if there isn't, then add one. If that makes sense!

Also, would be great to put an updates checker in the backlog. Cheers.
