### ISSUE TITLE
Measured colors in the main application window are not displayed correctly

### ISSUE THREAD

**Issue by Korb** [ThePacielloGroup/CCAe#172]
That is, the color is measured correctly, calculated according to standards, probably, too. But in the main window, the preview of this color does not match the displayed color code.

During pipetting, the magnified color view displays correctly.

![2020-06-07_11-27-04](https://user-images.githubusercontent.com/3509797/83964266-88beb280-a8b4-11ea-8d18-8f15f1d352ea.png)

Colour Contrast Analyser (CCA) 3.0.1.0 portable
Microsoft Windows 10.0.18363.836

**Comment by patrickhlauke** [comment]
Duplicate of https://github.com/ThePacielloGroup/CCAe/issues/76
