### ISSUE TITLE
Latest installers aren't digitally-signed

### ISSUE THREAD

**Issue by EricDunsworth** [ThePacielloGroup/CCAe#177]
**Describe the bug**
I noticed that the installers of older versions of CCAe (like v3.0.1 - released on March 19th) were digitally-signed, but newer versions (like 3.1.0 and 3.1.1) no longer seem to be.

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bit
 - Version 3.1.0 and 3.1.1

**To Reproduce**
Open the file properties of any one of CCAe's EXE or MSI installers.

**Expected behavior**
A "Digital Signatures" tab should be present and list at least one signature.

**Additional context**
I consider this to be different from #66 and #125 since the latest installers that existed when they were first created were digitally-signed.

**Comment by ferllings** [comment]
I'm sorry for the delay, I'm in the process of getting a EV Code certificate, and it takes a lot more time than I expected, to pass all the security checks
