### ISSUE TITLE
CCA Dropper not working

### ISSUE THREAD

**Issue by doikawa** [ThePacielloGroup/CCAe#182]
**Describe the bug**
After installing CCA, when clicking on the dropper it highlights the dropper and then goes away but does not bring up the magnifying glass. The dropper does not do anything... I have asked other people to try and it works on their computers just fine.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64-Bit Version 2004 (Build 19041.329)
 - CCA: Version 3.1.1

**To Reproduce**
Steps to reproduce the behavior: Tried uninstalling and reinstalling

**Expected behavior**
I would like to just click on the dropper to figure out the color HEX code

**Screenshots**

![image](https://user-images.githubusercontent.com/71020900/92610373-a02b8400-f285-11ea-848b-c244dce98704.png)

**Additional context**

**Comment by doikawa** [comment]
Can I please have some assistance with this?

**Comment by ferllings** [comment]
I would like to help.
But as I can't reproduce the issue it's difficult for me to fix it.
Could you try to see if you can open the dev console? `ctrl` + `shift` + `i`

**Comment by doikawa** [comment]
Sorry for the late response. We were able to open up the development console. What is the next steps?

**Comment by patrickhlauke** [comment]
is it showing any JS errors at all?

**Comment by doikawa** [comment]
Where will I have to look in the Dev. Console for the errors?

**Comment by doikawa** [comment]
Here is the error message I received:

**Comment by doikawa** [comment]
remote.js:20 Electron Deprecation Warning The 'remote' module is deprecated and will be disabled by default in a future version of Electron. To ensure a smooth upgrade and silence this warning, specify {enableRemoteModule: true} in the WebPreferences for this window.
(anonymous) @ remote.js:20
DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/CCA/resources/app.asar/src/views/focus-visible.min.js.map:

**Comment by doikawa** [comment]
I looked on a colleagues computer and it seems like they have the same error message but the dropper is not working. Once again when I select the dropper, it looks like it selects it but then does nothing and it will not allow me to pick the background as the magnifying glass with the pixels does not show up.

**Comment by ferllings** [comment]
Yes, the messages are not related.
Do you see any difference between your machine and your colleagues, is it the same Windows version?

**Comment by doikawa** [comment]
Same version of windows, here is the info:
Microsoft Windows 10 Pro
10.0.19041 N/A Build 19041

**Comment by TrippJD** [comment]
I am having this same issue. When I first installed the app 3 or 4 months ago the dropper worked fine. Then after a couple of weeks of use, it just stopped working. I just updated to the 3.1.1 version but still not working.
I get these errors in the console:

remote.js:20 Electron Deprecation Warning The 'remote' module is deprecated and will be disabled by default in a future version of Electron. To ensure a smooth upgrade and silence this warning, specify {enableRemoteModule: true} in the WebPreferences for this window.
(anonymous) @ remote.js:20
DevTools failed to load SourceMap: Could not load content for file:///C:/Program%20Files/CCA/resources/app.asar/src/views/focus-visible.min.js.map:

**Comment by TrippJD** [comment]
does anyone have a solution for this? The dropper is the only reason I use this app. It lets you click it once after starting the app, then the button turns blue, then your curser has no change at all and after clicking anywhere on the desktop the button goes back to its original color/look, After that, the button can't be clicked again it does nothing.

**Comment by doikawa** [comment]
TrippJD we were able to resolve the issue by installing an older version of the CCA application.

**Comment by TrippJD** [comment]
In case anyone is wondering, 1.2.1 is the latest version that I was able to get the eyedropper working in. Here is a link to that version.
https://github.com/ThePacielloGroup/CCAe/releases/tag/v1.2.1
Hopefully this issue will be fixed one day.

**Comment by ferllings** [comment]
This make sense as this was the last version using the JS version color picker.
