### ISSUE TITLE
Installation on MacOS not supported through Homebrew Cask

### ISSUE THREAD

**Issue by Jon-Schneider** [ThePacielloGroup/CCAe#186]
**Is your feature request related to a problem? Please describe.**
Homebrew itself is the de facto standard Mac package manager, and Homebrew casks are GUI Mac apps packaged for install via command line. 

See https://github.com/Homebrew/homebrew-cask for more info on casks, and https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md for information on creating a cask.

**Describe the solution you'd like**
CCAe can be installed via command line on Mac as a homebrew cask.

**Describe alternatives you've considered**
Mac App Store support would also be good, but it's probably easier to distribute via a cask. However, this does limit reach to non-engineers and requires a Mac App Store Subscription.

**Additional context**
While I'd be happy to contribute a patch if I were looking for a future feature request, since I'm not a representative of the project I'm not sure I can create a cask for you.

**Comment by ferllings** [comment]
As a brew user myself, it sounds like a good idea, I'll have a look.
You can create the cask but it wouldn't be signed.

Same for app store: I'll have a look to see how 'easy' is the process. The app is already signed and notarized. I hope this is just an extra step.

**Comment by Shrinks99** [comment]
Installed this application through Homebrew Cask today, happy to report that it is available now!

```shell
~ brew info --cask colour-contrast-analyser
colour-contrast-analyser: 3.1.2
https://developer.paciellogroup.com/resources/contrastanalyser/
/usr/local/Caskroom/colour-contrast-analyser/3.1.2 (144B)
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/colour-contrast-analyser.rb
==> Name
Colour Contrast Analyser (CCA)
==> Description
None
==> Artifacts
Colour Contrast Analyser (CCA).app (App)
==> Analytics
install: 5 (30 days), 23 (90 days), 108 (365 days)
```

**Comment by ferllings** [comment]
Awesome, I'll add that in the README
