### ISSUE TITLE
Installation aborts every time 

### ISSUE THREAD

**Issue by EleanorMee** [ThePacielloGroup/CCAe#188]
I'm having an issue installing the colour contrast analyser. I get this notification each time I try: installation aborted. 

![Instalation aborted](https://user-images.githubusercontent.com/73674957/97645575-2e67fd80-1ab2-11eb-9540-ca426f3d227c.JPG)

I'm using:
 - Windows 10 pro 
 - Version 1803

I'm wondering if either:
- I'm choosing the wrong folder to install to
- older versions of colour contrast analyser are conflicting with the new version
- there's a bug that affects the version of Windows I'm using.

Any recommendations for how to fix this? 

Thank you! I use this tool all the time in my work, and would love the newest version!

**Comment by ferllings** [comment]
While we are doing some tests, you can try the CCA-Portable64-3.1.1.exe version, which doesn't require any installation.
