### ISSUE TITLE
Color Picker Not Working

### ISSUE THREAD

**Issue by lindbech** [ThePacielloGroup/CCAe#191]
I just upgraded to the latest release. The color picker is only selecting black as an option (foreground and background). The picker circle displays black wherever I move it on screen.

I am using macOS Catalina (10.15.7). MacBook Pro (2016).

Is this a Catalina issue?

**Comment by ferllings** [comment]
Probably related to the screen permissions:
https://github.com/ThePacielloGroup/CCAe/issues/163

**Comment by clapierre** [comment]
On an a11y training call and everyone had the same issue its not working both PC and Mac
