### ISSUE TITLE
When using CCA tool - Malware warning is triggered

### ISSUE THREAD

**Issue by ghost** [ThePacielloGroup/CCAe#194]
**Describe the bug**
When I select the color picker to identify a color, my security software indicates that this software is potentially a problem. 

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bits
 - Version 1909

**To Reproduce**

1. Open the application from my toolbar
2. Select the color picker (I've selected the foreground first, as well as the background first - the end result is the same)
3. My systems security indicates there is a malware threat.
4. CCA application freezes - and will not respond until I select the X to close the application.
5. I am able to close and reopen the CCA application; however, the same issue occurs.

**Expected behavior**
1. Open the application from my toolbar
2. Select the color picker for foreground - CCA identified the #HEX 

**Screenshots**
![image](https://user-images.githubusercontent.com/75389184/101962668-c6412700-3bda-11eb-8b6b-a5f7bfa72ea4.png)

**Additional context**
I close the CCA application. Then I run webroot to scan for actual threats. No threats are found.
The application is marked as safe. I am not sure what is causing the issue.

**Comment by kaufman-bryce** [comment]
I can confirm this is occurring under WebRoot when attempting to use the color pickers with both a full install and portable executable under Windows 10 64 19042.746 using CCA v3.1.2.

However my application continues to function, I am simply unable to use it's built in color pickers.

**Comment by hbanham** [comment]
I have the same issue with v3.1.3 in Windows 10 64.
The other v3 releases all seem to have this problem too (portable or not) so I'm using v1.2.1 which does not trigger the WebRoot threat - hope that helps with debugging.

**Comment by ferllings** [comment]
This is probably the result of the method used to run the picker. It is signed, so I'm not sure why it is still considered as threat

**Comment by hbanham** [comment]
When installing v3.1.3, this Windows SmartScreen window shows up, whereas when installing v1.2.1, the SmartScreen doesn't show up - not sure if that's linked to the issue?
![image](https://user-images.githubusercontent.com/61966716/117330175-52efc880-ae8d-11eb-8eb2-5410fd6d06fe.png)

**Comment by ferllings** [comment]
Should be fixed with new signing certificate
