### ISSUE TITLE
Color Picker Always black

### ISSUE THREAD

**Issue by 82L** [ThePacielloGroup/CCAe#195]
The color picker is always showing black pixels. 
Not working at all on my pc

 - OS: Windows 10 64bit
 - Version 1909
(AMD Ryzen 7, Nvidia 1660 card)

**To Reproduce**
Trying the color picker tool

**Expected behavior**
Showing a circle with the colors under my mouse, instead show black

**Comment by ampersandwich** [comment]
I'm experiencing the same issue in Windows 10 Pro, version 10.0.17763 
![Untitled-1](https://user-images.githubusercontent.com/84588557/119173453-85b8c580-ba24-11eb-8a08-a6232f07e1a8.jpg)

**Comment by jillmugge** [comment]
I'm getting the same error. 
Win 10 Pro,  V 21H1
CCA -V 3.1.2

https://user-images.githubusercontent.com/1904863/126672829-115f59e1-6236-4dc6-987c-56622bbabc6a.mp4

**Comment by Kenmcook** [comment]
I too am getting the same error.

**Comment by mezapata** [comment]
I am also experiencing this same issue with the additional wrinkle that the color picker "window" flickers from white to black.
CCA: Version 3.1.4
OS: Windows 10 64-bit, version 19042.1165

**Comment by Lseaman2** [comment]
I have the same issue.  I have tried reinstalling but still get the black circle. I'm running Version 3.1.2. I also get an auto update error.
![Contrast analyser](https://user-images.githubusercontent.com/92277134/136714992-5f185f66-0efb-4b63-be28-a264d3c086bb.jpg)

**Comment by ferllings** [comment]
Could you try this build?
http://files.paciellogroup.com/CCA/CCA-3.2.0.zip

**Comment by ferllings** [comment]
Should be fixed with use of Eyedropper API

**Comment by Lseaman2** [comment]
There is no instruction or install file with this. What am I meant to do with it?

Kind regards

Linda Seaman

**Comment by ferllings** [comment]
This version has been released: https://github.com/ThePacielloGroup/CCAe/releases/tag/v3.2.0
