### ISSUE TITLE
Colour Contrast Analyser application window too tall

### ISSUE THREAD

**Issue by deconspray** [ThePacielloGroup/CCAe#196]
**Describe the bug**
When CCA is activated, the application window is too tall for my maximum resolution. The 1.4.11 Non-text Contrast (AA) panel heading is partially visible, yet not the test results.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Display resolution: 1366 x 768 (768 is the maximum height I can use for my company-provided computer)

**Colour Contrast Analyser (CCA) information**
 - Version 3.1.2

**To Reproduce**
Start application.

**Expected behavior**
The application window allows all content to be viewable within the application window.

**Screenshots**
![CCA-2021-01-11](https://user-images.githubusercontent.com/1461525/104190490-cc950f80-53e1-11eb-995f-fc4702cee32e.PNG)

**Additional context**

**Comment by Lindah9** [comment]
I use a lower resolution, too. I found that you can press CTRL+dash (-) to zoom out the CCA window. You can do that repeatedly to get the window as small as you want. Also, if you select the arrow to expand the AA section, it displays, even though it's hidden initially.

**Comment by deconspray** [comment]
The issue is resolved for me. While I was not able to zoom out of the CCA interface, I did have the preview panel in an expanded state (which went originally unnoticed). Thanks. I will close this issue.
