### ISSUE TITLE
Is there a way to gain access to older versions of the CCA tool?

### ISSUE THREAD

**Issue by vprentice** [ThePacielloGroup/CCAe#198]
**Is your feature request related to a problem? Please describe.**
Is there a way to gain access to older versions of the CCA tool?

**Describe the solution you'd like**
Ability to access older versions of the tool to download.

**Describe alternatives you've considered**
DNA

**Additional context**
DNA

**Comment by ferllings** [comment]
Yes, on the Releases page:
https://github.com/ThePacielloGroup/CCAe/releases
