### ISSUE TITLE
Anti-Virus reporting virus on color picker

### ISSUE THREAD

**Issue by kevtobias** [ThePacielloGroup/CCAe#203]
**Describe the bug**
My antivirus software (avast) is blocking the color picker due to an infection.  My backup software (Acronis) also reported this as potential ransomware.

Threat Name:
IDP.ALEXA.53

**Desktop (please complete the following information):**
 - OS: Windows 64 bit
 - Version 10
 - build: 19042.868
 - 
**To Reproduce**
Click the color picker (it happened for me on the foreground picker, I can't confirm if this also happens on the background picker)

**Expected behavior**
No virus detected

**Screenshots**

**Additional context**
This occurs on the current version of CCA (downloaded and installed today) and an older version (3+).

**Comment by ferllings** [comment]
Should be fixed with last signed version.
