### ISSUE TITLE
In my small screen, CCA is partly hidden and I can't resize the window so it's unusable

### ISSUE THREAD

**Issue by juliemoynat-tanaguru** [ThePacielloGroup/CCAe#205]
**Describe the bug**
I have a full HD screen with a 150% Windows zoom and CCA is partly hidden in my screen so it's unusable because I can't resize the window of the software.

**Desktop (please complete the following information):**
 - Windows 10 64 bits Pro
 - CCA Version 3.1.3

**To Reproduce**
Apply a zoom in your Windows and open CCA.

**Expected behavior**
I want to be able to resize the window so that I can have a scrollbar. Or if you can do a responsive software… :-D

**Screenshots**
<img width="373" alt="" src="https://user-images.githubusercontent.com/41478356/114042269-943c8a80-9885-11eb-986a-de5d62ea9eb3.PNG">

**Comment by ferllings** [comment]
Bonjour,

As tu essayé le zoom, dans le menu Affichage? Ou 'ctrl -' ?

**Comment by juliemoynat-tanaguru** [comment]
Bonjour,

Non, je n'avais pas essayé et effectivement, ça permet de voir le reste. Merci.
Par contre, ce n'est pas une solution totalement satisfaisante car le texte devient tout petit.

<img width="281" alt="" src="https://user-images.githubusercontent.com/41478356/114843522-3276a600-9dda-11eb-9054-ef767e70cf60.PNG">

**Comment by ferllings** [comment]
Je pense de toute façon changer complètement le design pour avoir qqchose de plus compact.

**Comment by juliemoynat-tanaguru** [comment]
Ah c'est une bonne idée, je pense :-)

Je ferme ce ticket dans la mesure où le zoom "corrige" mon problème même si ce n'est pas à 100% satisfaisant. Je serai attentive aux futures mises à jour !
