### ISSUE TITLE
Not signed by the applictaion owner

### ISSUE THREAD

**Issue by ferllings** [ThePacielloGroup/CCAe#208]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/2118130/114188256-3ffade80-9949-11eb-8771-d2750ecc9772.png)

**Comment by formspiel** [comment]
Same for me. I tried reinstalling but it doesn't help.

WIN10 Enterprise 1909
CCA 3.1.2

**Comment by A11yEvangel** [comment]
Same issue. Even trying to download the EXE is blocked (by Microsoft Edge) because it's not signed.

**Comment by jo9ty60** [comment]
I also receive this Auto Update Error message. Relates to version 3.1.4 (and previous version). Very frustrating every time I use this tool. When I receive the error message it also slows down the CCA and makes it somewhat unusable. Then I receive a "Not responding" message and need to close CCA and reopen to for one-use.
Any eta on a fix?

**Comment by jo9ty60** [comment]
See also related bugs - #158 and #162. Seems to be a fairly common issue.

**Comment by ferllings** [comment]
I'm working on it: I changed something on 3.1.4 certificate, so 3.1.5 should not raise an error.
Finger crossed...

**Comment by formspiel** [comment]
> I'm working on it: I changed something on 3.1.4 certificate, so 3.1.5 should not raise an error.
> Finger crossed...

Thanks for looking into it. Can I support you with a test/verification on my setup?
BR Andreas

**Comment by formspiel** [comment]
Sorry to bother you.
Is there any timeline when the next release will go public?

Your tool is the industry standard and many people rely on it. :)

**Comment by formspiel** [comment]
Any news on the fix and timeline?

**Comment by OLLI-S** [comment]
I have the **same issues**, when will **3.1.5** be released?
This is **urgent** because I want to use CCA at work.

**Comment by ArminWeb** [comment]
We (my colleagues and myself) are also having these messages, so it is really time for an update.
Please @ferllings release the new version!

**Comment by ferllings** [comment]
I understand your frustration.
The project is still active, and I have started to work on a major update.
but I have difficulties to find time to work on this project at the moment.

**Comment by OLLI-S** [comment]
@ferllings What about releasing a version that **just fixes this problem** and **does not have any other new features**?
So users can use the current version and there is no pressure to release a new version on  your side.

**Comment by A11yEvangel** [comment]
Thanks for you reply. We too (home and work) eagerly await the next update.

We'd also really like to be able to remove the older Classic edition, but cannot yet. It includes the screen simulation of varied vision deficiencies. We've found that *extremely* important in showing management the real problem with a specific design.
________________________________

**Comment by ArminWeb** [comment]
> @ferllings What about releasing a version that **just fixes this problem** and **does not have any other new features**? So users can use the current version and there is no pressure to release a new version on your side.

I like this suggestion....

**Comment by ferllings** [comment]
That should be feasible.

**Comment by formspiel** [comment]
Happy to see some action for this ticket!

What about charging for the software to maintain it? Open source always sounds nice but also requires time and skills.

You've set an industry standard with CCA and because you made it available for free there're no alternatives.

Hope you can find some time to release the changes.

**Comment by OLLI-S** [comment]
Sorry if I bother again:
There is still no new version released and the problem is still existing.
@ferllings When do you plan a fif for this issue?

**Comment by formspiel** [comment]
Happy birthday dear bug!

**Comment by ferllings** [comment]
Sorry for that delay.
I'm waiting to receive the new certificate.
I also trying to debug a problem on Windows, were the app simply doesn't start.

**Comment by OLLI-S** [comment]
@ferllings You closed this issue, but the last release of CCA was 4 weeks ago.
So, do you plan to release a new version soon (that includes the certificate) or is this already implemented in the current version?

**Comment by ferllings** [comment]
Hi @OLLI-S, the new certificate has been included in v3.2.
I forgot to close this issue at the same time.

**Comment by OLLI-S** [comment]
@ferllings Thank you for adding the certificate, I will try the new version tomorrow.
I did not find the "Certificate" issue in the Changelog of 3.2, so I asked my previous question.
