### ISSUE TITLE
Suppress/swallow click when using picker

### ISSUE THREAD

**Issue by patrickhlauke** [ThePacielloGroup/CCAe#21]
Not sure how feasible this is, but what currently happens:

- you choose color picker
- you move over, say, a button or link to pick up its color
- you click, the color gets recognised
- however, the click is also registered on whatever link/button/etc you clicked (potentially triggering stuff, going to a different page, etc)

Is there a way to suppress/swallow the click, so it doesn't propagate?

**Comment by ferllings** [comment]
I doesn't append on MacOS, I'll try on Windows

**Comment by ferllings** [comment]
I can't reproduce on Windows neither. Do you have a test case?

**Comment by patrickhlauke** [comment]
as rough as it is...did a quick iphone video recording https://www.dropbox.com/s/kyri7bdx4jnf1zo/Video%2023-08-2018%2C%2012%2048%2057.mov?dl=0

wondering now if perhaps this is related to the fact that the circle/color preview thing (on my Surface Pro) is not aligned with the mouse pointer yet

**Comment by patrickhlauke** [comment]
using 1.0.0-alpha4 and confirming that the problem disappeared with the pointer/circle issue being resolved now.
