### ISSUE TITLE
macOS Big Sur Icon

### ISSUE THREAD

**Issue by Shrinks99** [ThePacielloGroup/CCAe#210]
As you're probably aware by now, icons on macOS have a suggested defined shape whereas the icon for CCA just takes up the whole box.  Is this the end of the world?  Not really... but it might be nice to be a little more uniform?

I've made my own version and have been using it for a while now, I think it looks reasonably good!  Nothing groundbreaking here, just a slight gradient and drop shadow to make it a little less flat and help it fit in with the others.  Here it is in context:

<img width="414" alt="Screen Shot 2021-04-15 at 5 30 13 PM" src="https://user-images.githubusercontent.com/5672810/114940969-88fed700-9e10-11eb-9ff0-b1449704320a.png">

**Alternatives**
There was an alternate version posted on https://macosicons.com created by Chris Mount but the website database was hacked and you can't view it anymore.  For what it's worth I liked my version better but hey, everyone has opinions.

If you'd like to use my version or make changes to it I'd be happy to give it to you / submit a PR, currently I believe you use a .icns file for the macOS icons, this new version has been designed for use with the Display P3 gamut and [Apple doesn't recommend using .icns anymore for this reason](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon#app-icon-attributes).  Not _entirely_ sure what implementation looks like to that effect... I just know how to make the PNGs properly!

**Comment by ferllings** [comment]
Thanks,
Yes, if you can drop me the icon, I'll use it.
I don't know if I should replace the Windows version as well or keep the squared version...

**Comment by Shrinks99** [comment]
Will do after the 21st and post here with a Dropbox link?

If you want to make a version for Windows I could probably sort that out as well?  I've replicated their fluent logo styling in the past, alternatively it could just stay how it is as there's not real established standard on Windows.  Maybe round the corners off a bit?

**Comment by Shrinks99** [comment]
Wow you can just send zip files right here, how convenient!  Source PSD and exported PNGs are included, note that if you save the PSD it will auto-rexport the PNG files but you'll have to re-apply the P3 profile outside of Photoshop to make sure the exported files have the correct colours.  No idea why that's the way it works but that's the only way I've been able to get Apple's template to actually export things and work properly.

Anyways, here's the icon!
[ColorContrastAnalyzer Icon.zip](https://github.com/ThePacielloGroup/CCAe/files/6370974/ColorContrastAnalyzer.Icon.zip)
