### ISSUE TITLE
The Colour Contrast Analyser picks up my desktop photo and not the files I have up. I am working in InDesign on BigSur. My snslyser worked up until I downloaded Big Sur. Please help me figure this out?

### ISSUE THREAD

**Issue by akleebank** [ThePacielloGroup/CCAe#216]
**Describe the bug**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 32 bits]
 - Version [e.g. 1.0.0]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by ferllings** [comment]
Hi,

You need to set  "Screen Recording" for CCA:
 "System Preferences" > "Security & Privacy" > "Privacy" tab > "Screen Recording"
