### ISSUE TITLE
Picker only working on desktop background but not in browser, apps, etc.

### ISSUE THREAD

**Issue by michelleamorgan** [ThePacielloGroup/CCAe#217]
When I select the picker, it will correctly identify the color of anything on my actual desktop, but when hovering over a webpage or application, it does not select the right color. 

**Desktop (please complete the following information):**
 - OS: Big Sur 11.3.1
 - Version: 3.1.2

**To Reproduce**
Unclear since this is only happening with my version. I've uninstalled and reinstalled several times. 

**Expected behavior**
Picker should select the correct color value when it hovers.

**Screenshots**
Attached
<img width="1680" alt="Screen Shot 2021-08-03 at 12 00 53 PM" src="https://user-images.githubusercontent.com/29584961/128048293-f0d9ea9e-b6c8-491b-8ac9-501e92742ca2.png">
<img width="1680" alt="Screen Shot 2021-08-03 at 12 00 58 PM" src="https://user-images.githubusercontent.com/29584961/128048310-2b156094-3ae9-4e29-9b05-62d8721bceb0.png">

**Additional context**

**Comment by Suriv** [comment]
Download the latest version to see if the problem continues

actual versión 3.1.4

https://github.com/ThePacielloGroup/CCAe/releases

**Comment by ferllings** [comment]
This is a configuration issue. Look here: https://github.com/ThePacielloGroup/CCAe/issues/163
