### ISSUE TITLE
change tooltip for background colour NOT to mention alpha/transparent colors

### ISSUE THREAD

**Issue by patrickhlauke** [ThePacielloGroup/CCAe#22]
Entering rgba or similar as background color is flagged as an error (as obviously CCA can't guess what's underneath and do its proper calculation) ... but the tooltip still says rgba etc are valid entries

![capture](https://user-images.githubusercontent.com/895831/43907626-ce35c22a-9bed-11e8-814b-515c11dd3702.PNG)

![capture2](https://user-images.githubusercontent.com/895831/43907786-3621979c-9bee-11e8-9b0a-34d6f999ebb5.PNG)

(note that #FFFFFFFF, rgba, hsla are given as valid examples)

**Comment by patrickhlauke** [comment]
also not that `#FFFFFFF` there is probably really `#FFFFFFAA` ?

**Comment by ferllings** [comment]
I can't replicate it. What version do you use?

**Comment by patrickhlauke** [comment]
pretty sure it's the latest release from 20 days ago (but related: https://github.com/ThePacielloGroup/CCAe/issues/28)

I'll download the latest release and double-check

**Comment by patrickhlauke** [comment]
ok, using the latest version, i now don't get the warning triangle/red underline. weird, perhaps i still had the older preview release installed.

**Comment by patrickhlauke** [comment]
ah sorry, i kind of mashed up two separate issues into this one bug. let me rename/reword this. the issue of the rgba showing the warning for FOREGROUND is resolved, but the tooltip for the BACKGROUND should not mention RGBA, HSLA, #FFFFFFAA (so you'd likely need two separate tooltips, one for foreground that does mention the transparent ones, one for background which doesn't)

**Comment by patrickhlauke** [comment]
even more odd, it seems to be ok with hex-based transparent colour (how would it calculate this? would it assume the underlying colour behind the background is white?), but not happy with rgba and hsla

![c1](https://user-images.githubusercontent.com/895831/44515097-95f7b680-a6b9-11e8-9daa-416339156bbb.PNG)

![c2](https://user-images.githubusercontent.com/895831/44515110-9b550100-a6b9-11e8-8ca8-db529073749a.PNG)

![c3](https://user-images.githubusercontent.com/895831/44515121-9ee88800-a6b9-11e8-892f-2471919c8fda.PNG)
