### ISSUE TITLE
My Account en OpenCart.abstracta.us

### ISSUE THREAD

**Issue by anaLeticiaPiris** [ThePacielloGroup/CCAe#220]
**DESCRIPCIÓN DEL ERROR**
Se realizó una prueba de contraste de colores con la aplicación Colour Contrast Analyser, en el sitio web opencart.abstracta.us, para la acción "My Account", dónde se encontró que la relación de colores entre el primer plano y el fondo no están acordes a los contrastes de colores definidos por la WCAG 2.1. Muestra fallas tanto para texto normal como para largo. 

**ESCRITORIO :**
 - OS: [ Windows 10 Home 32 bits]
 - Version [21H1]

**REPRODUCIR**
1- Abrir el sitio web opencart.abstracta.us.
2- Abrir AAC(Colour Constrast Analyser).
3- En AAC, a) en Foreground colour, seleccionar el "cuenta gotas", ir al sitio web y seleccionar un pixel , el mas nitido del texto y 
                     con click toma el dato.
                 b) en Background colour, seleccionar el "cuenta gotas", ir al sitio web y seleccionar un pixel  del color del fondo, 
                     con click toma el dato.
4- más abajo, en dónde dice WCAG 2.1 results muestra el resultado de la selección.

**COMPORTAMIENTO ESPERADO**
Se esperaba que el resultado sea el correcto, mostrando todos los items en verde con el visto de que estaba correcto.

**CAPTURA DE PANTALLA**

![Captura de pantalla (781)](https://user-images.githubusercontent.com/82429041/130359540-9dfa6fcb-ee21-4241-acc7-537e4f411f10.png)

**Comment by ferllings** [comment]
Is it possible to get an English translation?
Thanks
