### ISSUE TITLE
Tertiary field needed for transparency between text and background

### ISSUE THREAD

**Issue by anevins12** [ThePacielloGroup/CCAe#226]
**Is your feature request related to a problem? Please describe.**
When retrieving the color contrast of text on a transparent background, the foreground and background fields are taken to achieve contrast of the background field. What does this mean? In order for the foreground transparency to apply correctly, the background field needs to be set to reflect the actual background of the element you're testing. For instance, if testing a foreground transparency of `#0000000a`, this results in light grey if the background field is set to `#ffffff`. If the background field is set to `#000000` then the foreground transparency will result in dark grey.

While that's a little cumbersome it's still fine for testing the background transparency behind the text, but it excludes the ability to test text color. Where can you test the contrast of text on transparent background? All the fields are taken. 

**Describe the solution you'd like**
A tertiary field that allows testing of text on top of alpha backgrounds.

**Describe alternatives you've considered**
Using the color picker tool to pick out the hex value instead of using the alpha format.

**Comment by patrickhlauke** [comment]
If CCA were to start down this path, you'd then also need an extra field if the background behind the background has transparency as well, potentially ad infinitum.  As it wouldn't be possible/sustainable, we're limiting this to just having foreground/background, and only catering for foreground transparency. Indeed in situations where you have further layers of transparency (the background, possibly even the background behind that one, etc), using the colour picker is the only sensible option.
