### ISSUE TITLE
Spanish language version

### ISSUE THREAD

**Issue by maserin** [ThePacielloGroup/CCAe#228]
I noticed that you already make your app available in ~6 languages, and I'm hoping you would consider adding Spanish. As there are 580 million Spanish speakers in the world, I feel this would vastly expand the reach of your app and the good that it could produce in the world. In my case, I'd love for the Spanish-speaking design team at my agency to be able to more easily understand and use your app to ensure that we are designing accessible websites for our clients. Thanks for your consideration!

**Comment by ferllings** [comment]
Hi @maserin,
The other translations have been provided by users.
As you can see in the "About" dialog.
Feel free to provide a Spanish version of the en.json file and I'll add it to the next release.
https://github.com/ThePacielloGroup/CCAe/tree/master/src/views/translations

You can upload the file here, or via a Pull Request.
