### ISSUE TITLE
Use EyeDropper API when it lands in Electron

### ISSUE THREAD

**Issue by patrickhlauke** [ThePacielloGroup/CCAe#229]
* https://github.com/WICG/eyedropper-api
* https://developer.chrome.com/blog/new-in-chrome-95/#eyedropper
* demo https://eyedropper-sample.glitch.me/

**Comment by ferllings** [comment]
That works so great !!
I need to do some tests on color spaces, but this is already a huge step.

Thanks Patrick

**Comment by ferllings** [comment]
Looks like electron 16 alpha, uses Chrome 96. I'll do some tests on it.

**Comment by patrickhlauke** [comment]
Perfect :)

**Comment by patrickhlauke** [comment]
https://patrickbrosset.com/articles/2021-11-24-how-i-built-an-eye-dropper-browser-extension/

**Comment by ferllings** [comment]
I'm currently working on it, but I have some difficulties to migrate from Electron v12 to v16.
But my initial test with the EyeDropper api was successfull.
The only issue with it is that it is not movable using the keyboard (yet?)

**Comment by patrickhlauke** [comment]
> The only issue with it is that it is not movable using the keyboard (yet?)

possibly worth filing a bug/request for chrome (and then any other browser that implements it)

**Comment by ferllings** [comment]
I've also left a comment here:
https://github.com/WICG/eyedropper-api/issues/22

**Comment by patrickhlauke** [comment]
Yay!

**Comment by ferllings** [comment]
Big disappointment, there is a bug in Electron/Window 10:
https://github.com/electron/electron/issues/27980
