### ISSUE TITLE
EXE and DLLs are executed from user temp folder when app is used, after installation

### ISSUE THREAD

**Issue by dhssectest** [ThePacielloGroup/CCAe#230]
**Is your feature request related to a problem? Please describe.**
Both Program Files installations, and portable executions of CCAe, will launch separate executables and dlls from random user profile temp folders.

Example, regardless of install type, the following files launch:
%OSDRIVE%\USERS\TESTJEREMY\APPDATA\LOCAL\TEMP\1UYULYWOAN3PZNKR6KPYNSRZFXD\COLOUR CONTRAST ANALYSER (CCA).EXE
%OSDRIVE%\USERS\TESTJEREMY\APPDATA\LOCAL\TEMP\1UYULYWOAN3PZNKR6KPYNSRZFXD\FFMPEG.DLL
%OSDRIVE%\USERS\TESTJEREMY\APPDATA\LOCAL\TEMP\1UYULYWOAN3PZNKR6KPYNSRZFXD\LIBEGL.DLL
%OSDRIVE%\USERS\TESTJEREMY\APPDATA\LOCAL\TEMP\1UYULYWOAN3PZNKR6KPYNSRZFXD\LIBGLESV2.DLL

This makes it difficult to whitelist in a corporate environment.

The executable is publisher signed by "O=TPG INTERACTIVE, LLC, L=CLEARWATER, S=FLORIDA, C=US" which is great and easily whitelisted.
However, the .dlls are not, and whitelisting the whole temp folder for .dlls is not a secure best practice.

**Describe the solution you'd like**
I have not seen any other applications which launch dlls/exes from user temp folder like this.
Only when an application is installed. Is there a need for it to write & execute new .exe/.dlls each time the app is used?
Is it possible for the app to be self-contained?

**Describe alternatives you've considered**
I can't think of any alternative solutions here.

Thank you

**Comment by ferllings** [comment]
Thanks for the info.
I'm working on MacOS and I didn't know that Electron was packaging some additionnal ddls.

It's seems that can be easily fixed with an option in electron-builder: https://stackoverflow.com/questions/69174622/code-signing-dll-files-with-electron-builder

But it might not be neccessary after #229
