### ISSUE TITLE
Color code picked from CCA tool is varying from the original color code

### ISSUE THREAD

**Issue by Gopi916** [ThePacielloGroup/CCAe#234]
Desktop:
 - OS: [Windows 10 64 bits]
 - Version [21H1]
 - CCA [Version 3.1.2]
 
Issue Description:
When I was checking one of our test pages, I observed the colour code which I am getting from the tool and the actual colour code from the developer code are varying.
I have attached the below snippet for your reference. In the below example, the colour code which I get from tool is ‘BCBCC0’ and from developer code is ‘ADABAB’

Expected: 
There should be any variation between the color code which I get from tool and from developer code.

Screenshot:
![image](https://user-images.githubusercontent.com/61313055/146974485-6b16e068-fcbd-4b2f-8277-0980cc47141b.png)

**Comment by ferllings** [comment]
Hi,

 This is a known problem with colorspaces: CCA and your browser are not in the same colorspace.
