### ISSUE TITLE
CCA Selecting Desktop colors behind target documents on new M1 Mac

### ISSUE THREAD

**Issue by igotabeme2** [ThePacielloGroup/CCAe#235]
**Describe the bug**
I am attempting to sample several colors from a document (PDF) and the eyedropper tool seems unable to see anything other than my desktop. So the tool is selecting desktop colors beneath the document I'm aiming for.

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - Version MacBook Pro (16-inch, 2021), Apple M1 Max

**To Reproduce**
Steps to reproduce the behavior: Simply launch CCA and attempt to sample color from any file (PDF, InDesign, Preview, Excel, Outlook, etc.). Notice that no color within any of these applications is selected. Color selection is from the desktop background only.

**Expected behavior**
I am expecting color sample information to be representative of the color I am actually looking at and that is directly beneath the CCA eyedropper tool. I have used CCA many times before and it has behaved as expected. However, this is the first time I've attempted to use it since upgrading to the new MacBook Pro, M1 Chip.

**Screenshots**
![IMG_9020](https://user-images.githubusercontent.com/96840367/147693101-fc21fc95-16d4-4050-b92b-1390bc771493.jpg)

**Additional context**
Several things I've done to try and fix the issue:
1) I closed and relaunched the CCA software several times.
2) I reinstalled the software.
3) I checked for updates and installed the latest version, bringing me up to 3.1.4
4) I've tried sampling color from other files (InDesign, Preview, Excel, and Outlook) and the same thing is happening.

**Comment by ferllings** [comment]
https://github.com/ThePacielloGroup/CCAe/issues/163
