### ISSUE TITLE
CCA Does not show up when opened

### ISSUE THREAD

**Issue by d8kline** [ThePacielloGroup/CCAe#236]
**Describe the bug**
When I open CCA, I can see the tool icon in my tool bar, but the panel does not show up on my screen. I have uninstalled and reinstalled CCA but the same issue occurs. Does it matter if I am using two screen displays? How can I get CCA to be visible and functional?

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro  Intel(R) Core(TM) i7-4910MQ CPU @ 2.90GHz   2.90 GHz
     Installed RAM	16.0 GB   64-bit operating system, x64-based processor
 - Version 20H2  OS Build: 19042.1466  Windows Feature Experience Pack 120.2212.3920.0

**To Reproduce**
Open a web page or document to check for colour contrast
Open the CCA 3.1.2 by clicking on start and selecting Colour Contrast Analyzer (CCA)
A CCA tool icon shows up in my toolbar, but the tool does not appear in my screen view. 

**Expected behavior**
I expect that the tool would show up on my screen so that I can select and analyze the various colors on the webpage or document.

**Screenshots**
![CCA Issue](https://user-images.githubusercontent.com/61714400/152394251-c99a32c4-3d22-439e-8a3d-478300ab471f.png)

**Additional context**

**Comment by RunemasterP** [comment]
Hello there, I was able to get this to show up by doing the following:

1. Hover over the icon until the preview fully appears;
2. Right click on the preview and select 'Move';
3. Hold down the right or down arrow keys;
4. Hit 'Enter', the window should appear.

Hope this helps!

**Comment by ferllings** [comment]
Please try v3.2.0 to see if you can still reproduce

**Comment by turbolego** [comment]
> Hello there, I was able to get this to show up by doing the following:
> 
> 1. Hover over the icon until the preview fully appears;
> 2. Right click on the preview and select 'Move';
> 3. Hold down the right or down arrow keys;
> 4. Hit 'Enter', the window should appear.
> 
> Hope this helps!

I had the same issue with both CCA-Portable-x64-3.4.2 and CCA-Setup-3.5.2.
Issue resolved after running CCA-Portable-x64-3.4.2 and moving the window as instructed by @RunemasterP 
After moving the window with I had the same issue with both CCA-Portable-x64-3.4.2 and CCA-Setup-3.5.2.
Issue resolved after running CCA-Portable-x64-3.4.2 the issue was also resolved for CCA v.3.5.2 that i re-installed after running CCA-Portable-x64-3.4.2

**Comment by sulazix** [comment]
I have the same issue but only when working with 1 screen, I have a 2 screen setup at work => no issue at all 

1 screen setup at home and when working with the "native" screen of my laptop => the window is outisde

**Comment by ferllings** [comment]
@sulazix I assume this is the same laptop?
If so, it probably try to re-position itself on the 2nd monitor, even if the 2nd monitor is not plugged.
To confirm, could you try, at work, to position CCA on your main screen, then close it?
Then, at home, it should display properly.
