### ISSUE TITLE
colour picker only picking colors from desktop

### ISSUE THREAD

**Issue by LRivian** [ThePacielloGroup/CCAe#237]
**Describe the bug**
when using the colour picker, it immediately picks the shade off my desktop wallpaper and locking it in - even when a window is over the top. Not allowed to pick other colors.
**Desktop (please complete the following information):**
 - OS: Mac OS
 - Version  12.2.1

**To Reproduce**
Steps to reproduce the behavior: click colour picker.

**Expected behavior**
when clicking colour picker I'd expect to be able to a) pick the colour I need/want and b) not to lock in a colour that the application seemingly picks from desktop c) if the previous does happen then be allowed to select colour that isn't part of my desktop
**Screenshots**

**Additional context**
<img width="1792" alt="Screen Shot 2022-03-08 at 09 32 48" src="https://user-images.githubusercontent.com/101195366/157258760-6d4571d6-3e24-4cc3-bdfe-7f5ddfbfe225.png">

as of this moment and with this current implementation using colour picker in CCA is useless.

**Comment by ferllings** [comment]
Duplicate https://github.com/ThePacielloGroup/CCAe/issues/163
