### ISSUE TITLE
CCA not working after upgrade to Monterey

### ISSUE THREAD

**Issue by abbyclarkcainc** [ThePacielloGroup/CCAe#241]
**Describe the bug**
The eye dropper and other buttons in the window no longer work after I upgraded my OS to 12.3.1. I checked my system preferences and the permissions are set for accessibility and screen recording. I upgraded to the latest version of CCA, rebooted many times, still can't access the eye dropper tool or change color settings or get any of the buttons above the Sample Preview section of the window to function.

**Desktop (please complete the following information):**
 - OS: masOS Monterey 12.3.1
 - CCA Version 3.1.4

**To Reproduce**
Open CCA and try to use the eye dropper tool -- tool never engages.

**Expected behavior**
Open CCA and click the eye dropper tool, mouse changes to eye dropper and you can see a detailed view of the screen below to select a color sample.

**Screenshots**
<img width="606" alt="Screen Shot 2022-04-13 at 12 59 46 PM" src="https://user-images.githubusercontent.com/103594669/163232404-d28b352d-cfbe-499f-844b-a07ed30c909f.png">

**Comment by ferllings** [comment]
@abbyclarkcainc Do you use Apple M1?

**Comment by abbyclarkcainc** [comment]
I don't think so -- here are my laptop specs.

<img width="260" alt="Screen Shot 2022-04-14 at 9 02 26 AM" src="https://user-images.githubusercontent.com/103594669/163396158-62a63220-0cc2-467b-9738-5bc09367a3c4.png">

**Comment by debbiegijsbrechts** [comment]
I have exactly the same issue.
But I do have an M1.

**Comment by cmacarth** [comment]
Similar issue with macOS Monterey, but am able to move the eyedropper. However, it does not accurately identify the color which is main way it is being used (rather than inputting hex numbers that aren't known).

**Comment by abbyclarkcainc** [comment]
Checking back in to see if there has been a resolution -- or if someone knows of alternative app I could use? I tried Contrast from the Apple Store and found it to be unreliable, showing inaccurate contrast ratios.

**Comment by ferllings** [comment]
Could you try this build?
http://files.paciellogroup.com/CCA/CCA-3.2.0.zip

And let me know if it works for you?

**Comment by debbiegijsbrechts** [comment]
@ferllings for me it works perfectly now.
Thank you, you've made my weekend!

**Comment by ferllings** [comment]
@debbiegijsbrechts  Good.
I'm currently stuck with the Windows build, which prevents me to officially release both.

**Comment by abbyclarkcainc** [comment]
I'm getting an error message when I try to install

<img width="282" alt="Screen Shot 2022-05-20 at 9 58 16 AM" src="https://user-images.githubusercontent.com/103594669/169543826-d84bb72a-4e04-49dd-b02e-e875c742ba61.png">

**Comment by ferllings** [comment]
Right clic on the app, then choose "Open".
You should see a similar message, but this time with an "Open" button.
This a protection method from Apple, I'm not sure why because it is signed and notarized...

**Comment by abbyclarkcainc** [comment]
@ferllings That worked! And it works!!!! THANK YOU!!!!
