### ISSUE TITLE
CCA only can only select colours of the underlying desktop background

### ISSUE THREAD

**Issue by jack-skerrett-oak** [ThePacielloGroup/CCAe#242]
**Describe the bug**
When selecting colours, the colour picker ignores any windows you have open and instead just selects the colour of the underlying desktop background.
**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Version 12.3.1
 - Apple M1

**To Reproduce**
- Install CCA on the above set up
- Click one of the dropper tools
- See that it cannot select colour from anything except the background

**Expected behavior**
Given the dropper tool has been selected
When the user hovers over a window
Then the dropper tool can select a colour from that window

**Screenshots**
![Screenshot 2022-04-25 at 13 46 54](https://user-images.githubusercontent.com/102532470/165091913-ef116d4e-d2e3-480e-aa02-b5ed49eb5266.png)
**Additional context**

**Comment by ferllings** [comment]
See https://github.com/ThePacielloGroup/CCAe/issues/163 for solution
