### ISSUE TITLE
Odd coloured highlight for top-level menus on Windows

### ISSUE THREAD

**Issue by patrickhlauke** [ThePacielloGroup/CCAe#251]
**Describe the bug**
The menus ("Colour Contrast Analyser (CCA)", "Edit", "View", "Development") have a strange dark pink hover/highlight colour

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit

**To Reproduce**
Open the latest 3.2.0 on Windows, hover over the menus

**Screenshots**

![screenshot of the top of CCAe, showing the dark pink highlight/hover](https://user-images.githubusercontent.com/895831/178520844-7fb9317c-e7d5-41e5-8bd0-c6ba3532ecd4.png)

**Comment by patrickhlauke** [comment]
Filed this, as it seems it's either something fundamentally borked on my machine, or it's a problem in electron itself https://github.com/electron/electron/issues/34939

**Comment by ferllings** [comment]
Fixed in Electron/Chrome

**Comment by patrickhlauke** [comment]
Goodness, at last. I had already given up on electron folks here...

**Comment by patrickhlauke** [comment]
Will the change to electron roll out in the next release? The current latest still has the pink menus

**Comment by ferllings** [comment]
Let's re-open until I re-check this.

**Comment by patrickhlauke** [comment]
Seems to have been fixed now (ironically, it now uses a super-non-contrasty grey inside the menu itself ... at least for the top level menus, it also gives an outline when using the keyboard)

![screenshot of the latest version of CCA/Windows, with a light grey highlight](https://github.com/ThePacielloGroup/CCAe/assets/895831/d96c5432-2779-4379-bee0-e725ff09a0c9)
