### ISSUE TITLE
ColorPicker v3.2 not working Win 10

### ISSUE THREAD

**Issue by ipegmarc** [ThePacielloGroup/CCAe#253]
It works on computers that don't have all the updates like I list below. But does not work on this computer.

Edition	Windows 10 Enterprise
Version	21H2
Installed on	‎7/‎12/‎2022
OS build	19044.1826
Experience	Windows Feature Experience Pack 120.2212.4180.0

**Comment by ferllings** [comment]
Duplicate #264
