### ISSUE TITLE
Always on Top = Off setting does not work on app launch

### ISSUE THREAD

**Issue by gradyat** [ThePacielloGroup/CCAe#254]
**Describe the bug**
The app does not follow the **Always on Top** = Off setting upon app launch. The setting appears as Off upon app launch, but the app acts as if it is On. Turning **Always on Top** On then Off fixes the issue for that session. The user's setting of **Always on Top** = Off does not persist after quitting and relaunching the app.

**Desktop:**
 - OS: macOS Monterey 12.4
 - Version 3.2.0

**To Reproduce**

1. Open CCA
2. Go to View in menubar and observe that **Always on Top** is unchecked
3. Click a window behind
4. Observe that CCA stays on top
5. Go to View in menubar and turn the **Always on Top** setting on, then turn it off.
6. It follows the off setting for that session.

**Expected behavior**
CCA should always follow the user's **Always on Top** setting.

**Comment by patrickhlauke** [comment]
Confirming same behaviour on Windows (just came here to file an issue).

I'd expand this further to say that the setting (whether the user chose to have it "Always on Top" or not), should be saved/stored when the app is closed, and set back to that when the app is launched.
