### ISSUE TITLE
Version number is missing in the About window

### ISSUE THREAD

**Issue by gradyat** [ThePacielloGroup/CCAe#255]
**Describe the bug**
The version number is missing in the About window. It only says "Version".

**Desktop:**
 - OS: macOS Monterey 12.4
 - Version 3.2.0

**To Reproduce**

1. Open CCA
2. In the menubar, go to Colour Contrast Analyser > About.
3. Observe that the version number is missing.

**Expected behavior**
The version number should appear.

**Screenshots**
<img width="486" alt="Screenshot of the Colour Contrast Analyser About window which has the word Version but no number" src="https://user-images.githubusercontent.com/35243100/180579245-c769c111-932d-4c0a-a375-0d0d81f41b1b.png">
<img width="734" alt="Mac Finder Applications Quick Look for Colour Contrast Analyser.app which shows the version number 3.2.0" src="https://user-images.githubusercontent.com/35243100/180579321-b1e7cb0f-fdfa-418b-959d-48261482c105.png">

**Comment by PatUMW** [comment]
I have the same situation

**Comment by OLLI-S** [comment]
Seem 3.2.0 is a bit buggy.....
