### ISSUE TITLE
CCA eyedropper doesn't work on Mac, either.

### ISSUE THREAD

**Issue by MarkMcDe** [ThePacielloGroup/CCAe#259]
Ive tried both 3.1 and 3.2 of the CCA, and the Eyedropper tool does not allow me to select any colors outside of the panel for the Eyedropper tool itself, let alone the screen of a different application. 
Running a Mac with Monterey 12.5.

**Comment by ferllings** [comment]
Have you granted screen permission?

(System Preferences > Security & Privacy > Privacy > Screen Recording) and restart CCA

**Comment by MarkMcDe** [comment]
Aha! That worked! Thanks!
Mark
