### ISSUE TITLE
Add basic build instructions (in readme.md)

### ISSUE THREAD

**Issue by patrickhlauke** [ThePacielloGroup/CCAe#26]
Would be nice to have the basic build steps required (maybe even prefacing with a link to https://electronjs.org/docs/development) to clarify to noobs (like me) how to get at least a basic build running, how to test locally, etc.

**Comment by poorgeek** [comment]
Ideally this will only need to written for developers or those wishing to contribute as our officially releases would be built and published via Travis.

**Comment by patrickhlauke** [comment]
:+1:
