### ISSUE TITLE
Window "About CCA (F1)" opens links with attr "_self" instead of "_blank"

### ISSUE THREAD

**Issue by PatUMW** [ThePacielloGroup/CCAe#260]
When opened window "About CCA" and click in any link, website was downloaded and opened in CCA window. Screenshot below.
In previous versions CCA there is no such problem.
![image](https://user-images.githubusercontent.com/110469155/185343463-578b5e25-34d9-4a80-b554-3c715d807a1b.png)

**Comment by OLLI-S** [comment]
Same here (portable version).
Seem 3.2.0 is a bit buggy.....

**Comment by ferllings** [comment]
Fixed in 324b6d2101888c0a51794748c6c28b35b36d3228

**Comment by OLLI-S** [comment]
@ferllings When do you plan to release the new version?

**Comment by ferllings** [comment]
@OLLI-S maybe soon: I was hoping to release with a fix for the Windows picker, but the picker is really problematic. So I might just release without it.

**Comment by OLLI-S** [comment]
Releasing it soon would be much appreciated, thank you.
And I wish you and your family a happy new year!

**Comment by ferllings** [comment]
Happy New Year to you and familly too !
