### ISSUE TITLE
Doesn't work Ctrl+"+" shortcut for zoom in CCA

### ISSUE THREAD

**Issue by PatUMW** [ThePacielloGroup/CCAe#261]
**Describe the bug**
Doesn't work Ctrl+"+" shortcut

**Desktop (please complete the following information):**
 - OS: Win 10 Pro 64bit

**To Reproduce**
Open CCA
Try zoom in main window with shortcut (ctrl+"+") and not working

**Expected behavior**
Main window is zooming in
**Screenshots**
hard to catch screen 

**Additional context**
Shortcuts for zoom out and actual size works perfectly

**Comment by RiteshKumarPanda** [comment]
Actually I am facing this issue in CCA tool and I am not able zoom out so can you please suggest how can I solve.

**Comment by RiteshKumarPanda** [comment]
@PatUMW  can you please help above issue.
Issue : Suddenly CCA tool is zoom in ( it's showing too small window ) and I am not able to zoom out so can you please help on this.

**Comment by PatUMW** [comment]
> @PatUMW can you please help above issue. Issue : Suddenly CCA tool is zoom in ( it's showing too small window ) and I am not able to zoom out so can you please help on this.

@RiteshKumarPanda Try Ctrl+0 to reset zooming. It helps to me.
