### ISSUE TITLE
Shortcuts for pickers are not settable and shortcut for picker background doesn't work

### ISSUE THREAD

**Issue by PatUMW** [ThePacielloGroup/CCAe#262]
**Describe the bug**
Shortcuts for pickers are not settable and shortcut for picker background doesn't work. Tried with 2 scenarios

**Desktop (please complete the following information):**
 - OS: Win 10 Pro 64bit

**To Reproduce**
scenario #1
open CCA
open window 'Preferences' and set shortcut for picker foreground - F2 and for picker background F3
try both new shortcuts and both not working
extra: whereas old shortcut for picker foreground (F11) works (sic!?)

scenario #2 
open CCA
try default shortcut for picker background (F12) and not working

**Expected behavior**
Both pickers are settable in window "Preferences" and picker background works.

**Screenshots**
![image](https://user-images.githubusercontent.com/110469155/185350383-f9dec858-ad67-4947-ba37-033382399c7d.png)

**Comment by Chanvannak52** [comment]
1245[]()
