### ISSUE TITLE
CCA 3.2.0 - MSI installer missing

### ISSUE THREAD

**Issue by christophvw** [ThePacielloGroup/CCAe#265]
CCA 3.2.0 - MSI installer missing

How should we deploy this software now?

The EXE installer is no valid alternative as it does not seem to have a silent install switch:
https://github.com/ThePacielloGroup/CCAe/issues/244

**Comment by OrangeMinion** [comment]
"CCA-Setup-3.2.0.exe /allusers /S" works Ok for me

**Comment by ferllings** [comment]
Related to https://github.com/electron-userland/electron-builder/issues/7248
