### ISSUE TITLE
CCA 3.2.0 - Specific colour value not giving correct ratio

### ISSUE THREAD

**Issue by Aircl0wn** [ThePacielloGroup/CCAe#269]
**Describe the bug**
Contrast value not updating for specific colour, others working correcly

**Desktop (please complete the following information):**
 - OS: MacOS 12.6, M1
 - Version CCA 3.2.0

**To Reproduce**
I Have screen recording premissions set correctly
Pick two colours using the picker, get proper ratio results.
Pick white (#FFFFFF) as a background
Pick / set #009FDF as second colour.
Values doesn't update.

Repeat with 3.1.4 : works as expected

**Expected behaviour**
Repeat with 3.1.4 : works as expected as CCA gives the correct contrast ratio

**Screenshots**
Screenshot with incorrect ratio value, can used as picker sample
<img width="548" alt="image" src="https://user-images.githubusercontent.com/13189457/197739073-ce432263-d071-45a1-b4bb-a94844b6df6f.png">

**Comment by ferllings** [comment]
Confimed.

I need to fully investigate, but strangely this particular color doesn't seems to update the contrast ratio.
