### ISSUE TITLE
In cases wrong colour shown, not corresponding to hex

### ISSUE THREAD

**Issue by WillyLaudehr** [ThePacielloGroup/CCAe#273]
**Describe the bug**
Picker takes correct collour from screen, hex correct shown in field.
In cases demofields and preview uses different colour.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64bit
 - Version 21H2

**To Reproduce**
- Pick a colour from screen outside CCA-window, e.g. #42ABAD
- correct hex is detected, but shown colour is minimal different
- Test: Pick shown colour from demoregion, CCA reads #55ABAD
- Repeat: hex changes again, repeat, repeat... 
- at last colour stop at hex #C6BDEA
- 2nd e.g.: start at #CEEAFC

- suspicion: seems like only value of red differs

**Expected behavior**
Shown colour should be exact to picked up colour/hex

**Screenshots**
![grafik](https://user-images.githubusercontent.com/71374728/205033275-331618c0-2a3f-4e60-84ae-40ffe1289c73.png)

**Comment by ferllings** [comment]
Related to #76
