### ISSUE TITLE
Alternative portable version of CCA

### ISSUE THREAD

**Issue by OutshineIssue** [ThePacielloGroup/CCAe#282]
**Is your feature request related to a problem? Please describe.**
CCA is a great tool that I have been using for many years, now I have to work on a computer in which I cannot install programs because of admin rights.

**Describe the solution you'd like**
It would be wonderful to be able to use the program in a portable way, executable even from a pendrive.

**Describe alternatives you've considered**
I have used other programs but none as friendly as CCA.

**Comment by ferllings** [comment]
There is already a portable version:  CCA-Portable-3.2.0.exe
