### ISSUE TITLE
Contrast ratio not updated for certain colour values

### ISSUE THREAD

**Issue by patrickhlauke** [ThePacielloGroup/CCAe#287]
**Describe the bug**
Very rarely, there are certain colour combinations that cause a JS error and don't update the contrast ratio calculation

**Desktop (please complete the following information):**
 - Windows 11

**To Reproduce**

* open CCAe - by default, it will show `#000` against `#FFF` with a ratio of 21:1
* paste `#F56E00` into the foreground colour field
* the sample preview is correctly updated, but the contrast ratio shown remains 21:1

**Expected behavior**
Contrast ratio to be updated

**Screenshots**
Animated gif showing how pasting  `#F56E00` into foreground dosn't update the calculated contrast

![ccae](https://user-images.githubusercontent.com/895831/224578489-c7dd9655-a15a-4e18-a71f-2ea2273135b1.gif)

**Additional context**
Following error is shown in devtools console:

```
C:\Program Files\CCA\Colour Contrast Analyser\resources\app.asar\src\views\js\main.js:321 Uncaught ReferenceError: t is not defined
    at applyContrastRatio (C:\Program Files\CCA\Colour Contrast Analyser\resources\app.asar\src\views\js\main.js:321:56)
    at EventEmitter.<anonymous> (C:\Program Files\CCA\Colour Contrast Analyser\resources\app.asar\src\views\js\main.js:60:5)
    at EventEmitter.emit (node:events:526:28)
    at Object.onMessage (node:electron/js2c/renderer_init:69:746)
applyContrastRatio @ C:\Program Files\CCA\Colour Contrast Analyser\resources\app.asar\src\views\js\main.js:321
(anonymous) @ C:\Program Files\CCA\Colour Contrast Analyser\resources\app.asar\src\views\js\main.js:60
emit @ node:events:526
onMessage @ node:electron/js2c/renderer_init:69
```

**Comment by ferllings** [comment]
Hi Pat, nice to see you around.

This issue has been fixed in https://github.com/ThePacielloGroup/CCAe/commit/0e9a5cb8ccd63a9b80afe8c4000b79fe2bc4c777

**Comment by patrickhlauke** [comment]
@ferllings any chance that could be pushed to a new release then?

**Comment by ferllings** [comment]
Yes, I was waiting for few things, but I postponed for too long.
I'll just need to do #284 before releasing

**Comment by patrickhlauke** [comment]
thanks for the release today @ferllings ... confirming that this is now fixed :)
