### ISSUE TITLE
Seems to be producing incorrect results

### ISSUE THREAD

**Issue by markmagennis** [ThePacielloGroup/CCAe#292]
For the the colours #0073C4 & #F1F4F6 it reported a contrast of 4.9:1. Then a second time, for the same colours, it reported 1.6:1.

Both WebAIM (https://webaim.org/resources/contrastchecker/) and the aXe free browser extension report 4.47:1 for the same two colours.

See attached screenshots showing the output of the three tools.

Not sure which version this is as the About dialog doesn't show a number (see attached screenshot).

![image](https://user-images.githubusercontent.com/25799098/231405996-db07f15c-f26e-4927-8dde-68af94e885ed.png)

![image](https://user-images.githubusercontent.com/25799098/231404389-98849e58-f746-4624-b23e-135b872178e5.png)

![image](https://user-images.githubusercontent.com/25799098/231406924-13426631-2da4-409f-b7bd-86d070c79a13.png)

**Comment by ferllings** [comment]
Thanks @markmagennis : Please upgrade to v3.2.1, to see if it solves the "1.6" error.
Regarding the difference of contrast, with webaim, I need to do some test.

**Comment by markmagennis** [comment]
Thanks @ferllings I upgraded and now producing results in line with other tools. I don't know why I ended up with the wrong version. The one I had been using stopped working and another one appeared with "New" appended to its filename. That was the one that was in error.
