### ISSUE TITLE
Auto Update Error

### ISSUE THREAD

**Issue by nikolasgrigoriou** [ThePacielloGroup/CCAe#293]
**Describe the bug**
When activating the option to 'Auto Update' and then the new update has been downloaded, after clicking the 'Install Update' from the menu 'File > Install Update', the auto update error attached was displayed.

**Desktop (please complete the following information):**
 - Mac OS 13.3.1 (22E261)

**To Reproduce**
Steps to reproduce: Click on the 'Install Update', after the successful download of the package, by clicking to update from the menu, you receive the following error.

**Expected behavior**
It should have just installed the update.

**Screenshots**
<img width="372" alt="Screenshot 2023-04-13 at 3 59 25 PM" src="https://user-images.githubusercontent.com/130670330/231768279-613a592e-d5f1-4e1a-b028-4d1e31ff6264.png">

**Comment by ferllings** [comment]
Fixed in latest build process modifications
