### ISSUE TITLE
Expired Certificate

### ISSUE THREAD

**Issue by msamwill** [ThePacielloGroup/CCAe#294]
**Describe the bug**
Color picker not working windows 11.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11 64 bits]
 - Version [e.g. 22H2]

**To Reproduce**
Click color picker

**Expected behavior**
Can't use color picker, it is being blocked by applocker.  The color picker writes an executable to the users temp folder.  The executable has an expired certificate.  Therefore, publisher rule does not appear to work.  Do not want to use a path rule because the file name is generated and the rule would have to allow all .exe files in temp directory.

**Screenshots**
![image](https://user-images.githubusercontent.com/7591429/234620086-d147f2b6-e64a-4f28-ab54-42ceebb3af8c.png)

**Additional context**

**Comment by ferllings** [comment]
Thanks for the warning, I completely forgot to renew it.
I'll request a new one.

**Comment by msamwill** [comment]
Thank you!

From: ferllings ***@***.***>
Sent: Thursday, April 27, 2023 5:30 AM
To: ThePacielloGroup/CCAe ***@***.***>
Cc: Williams, Anna ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL]: Re: [ThePacielloGroup/CCAe] Expired Certificate (Issue #294)


Thanks for the warning, I completely forgot to renew it.
I'll request a new one.

**Comment by ferllings** [comment]
Closing, as the certificate has been updated and tested. Will be active for the next release
