### ISSUE TITLE
CCA doesn't open on my Mac

### ISSUE THREAD

**Issue by rionmaforever** [ThePacielloGroup/CCAe#298]
**Describe the bug**
Hello, I just downloaded CCA tool and it doesn't work on my computer.
The app is installed and I can open it. I can see CCA menues in my toolbar (on top of screen) but no window opens and most of the menues are grey, not clickable.

Preference system parameters are OK, I gave all permissions to CCA app like screen permissions, access to files, etc.
I tried with 3.3.0 and 3.2.0 versions --> Not working
Only 2.4.0 version is working, but it doesn't have all functionalities as latest version.

**Desktop :**
- MacBook Air (13 pouces, début 2014)
 - OS: BigSur 11.7.4

**Screenshots**
I have screenshots if necessary but I don't know how to upload them ;)

Many thanks in advance for your help

**Comment by ferllings** [comment]
I need to setup a virtual machine to test on BigSur.

**Comment by mhardyvallee** [comment]
I have the exact same issue on a more recent mac. MacBook Pro 15-inch 2018, using macOS Ventura 13.3.1 (a) (22E772610a).

**Comment by maddein** [comment]
I have the same issue my work device: MacBook Pro 16-inch 2023, with Apple M2 Pro and macOS Ventura 13.4.
I have the same problems as rionmaforever.

**Comment by juliennicouleaud** [comment]
Same issue here, MacBook Pro 13" M1 with Ventura 13.3.
Works with v3.2.0 though!

**Comment by ferllings** [comment]
I've added a logger to catch errors
Please try out v3.4.0 https://github.com/ThePacielloGroup/CCAe/releases/tag/v3.4.0
And send me your log folder: contact(AT)ferllings.me
- on macOS: ~/Library/Logs/{app name}/{process type}.log
- on Windows: %USERPROFILE%\AppData\Roaming\{app name}\logs\{process type}.log

**Comment by mhardyvallee** [comment]
Yes! This is working. Here’s my main.log.

De : ferllings ***@***.***>
Date : lundi, 7 août 2023 à 06:11
À : ThePacielloGroup/CCAe ***@***.***>
Cc : Hardy-Vallée, Michel ***@***.***>, Comment ***@***.***>
Objet : Re: [ThePacielloGroup/CCAe] CCA doesn't open on my Mac (Issue #298)
ATTENTION : Courriel externe, soyez vigilant.


I've added a logger to catch errors
Please try out v3.4.0 https://github.com/ThePacielloGroup/CCAe/releases/tag/v3.4.0
And send me your log folder: contact(AT)ferllings.me
·         on macOS: ~/Library/Logs/{app name}/{process type}.log
·         on Windows: %USERPROFILE%\AppData\Roaming{app name}\logs{process type}.log
