### ISSUE TITLE
Restrict Auto Update

### ISSUE THREAD

**Issue by cameron-rost** [ThePacielloGroup/CCAe#302]
Is there a way to restrict the option to enable auto updates entirely? Our team is trying too stay consistent between versions, which is easy enough to do by turning the feature off, but just wondering if there was a way to manage it. Maybe a plist that can be modified and then hosted in an MDM solution?

Requesting for macOS.

![Screen Shot 2023-07-17 at 11 22 08 AM](https://github.com/ThePacielloGroup/CCAe/assets/82844322/7dcb857e-b49b-48b1-951a-eb72b642b8b8)

**Comment by ferllings** [comment]
@cameron-rost What do you mean by entirely? The Auto-update stays off unless you manually activate it

**Comment by cameron-rost** [comment]
Our info sec team recommended turning the feature off since its a third party app and they want us to do due diligence on any updates. Good natured users might turn it on thinking it's a good idea and then they end up using a different version than the one we've approved for production. We also utilize Jamf as an MDM solution and deploy software, sometimes with specific versions or restrictions depending on the need. So if there is some kind of plist we can defaults write to, or maybe a distro we can curl specific versions from that'd be cool. But this is more of a nice to have and understand if a solution can't be provided. We'll just warn users not to enable to feature.

**Comment by ferllings** [comment]
I will add a config parameter to completely disable update checking.
In /Users/xxx/Library/Application Support/CCA/config.json,
switch `allowUpdates` to `false`

**Comment by cameron-rost** [comment]
Thank you for that. Is there an ETA for when the feature will be available? I tried implementing it by modifying the config.json and it appears to work by setting updates to disabled in the drop down menu. But I can still turn the feature on via settings.
