### ISSUE TITLE
Unattended Install options for Installing Colour Contrast Analyser (CCA) silently

### ISSUE THREAD

**Issue by AScott-WWF** [ThePacielloGroup/CCAe#303]
Hello,

We would like to deploy the Colour Contrast Analyser to a few of our staff's machines and as one of the Software deployment team I would like to know what the unattended install options are for Colour Contrast Analyser installer on Windows, we would be using Intune to deploy the software.
I have not managed to find any installation guidance on your website, but I read elsewhere that if you run the current installer (CCA-Setup-x64-3.3.0.exe) with a /s it installs silently, but are there any other installation options available?
For example: writing to a log file or setting or disabling any application settings (e.g. update check)
Thanks in advance

**Comment by ferllings** [comment]
@AScott-WWF I'm afraid not directly.
We use electron-builder to generate the installers
https://github.com/electron-userland/electron-builder/issues/4445

**Comment by AScott-WWF** [comment]
Ah perfect, That'll do what I was looking for
