### ISSUE TITLE
CCA doesn't open on my Win10 21H2

### ISSUE THREAD

**Issue by TLG95** [ThePacielloGroup/CCAe#304]
**Describe the bug**
I downloaded the last version of CCA (3.3.0) and installed it on physical device and virtual machine.
The installation is succesfull but when I try to execute the application from the shortcut in start menu folder or installation folder, the application won't show up. I can see 3 processes running in the tasksmgr.
Any help please ?

**Desktop :**
 - OS: Windows 10 64 bits 21H2 (19044.3208)

**To Reproduce**
Download installer from : https://github.com/ThePacielloGroup/CCAe/releases/download/v3.3.0/CCA-Setup-x64-3.3.0.exe
Install it
Start application

**Expected behavior**
The GUI show up

**Comment by moufid-elaroui** [comment]
I have the same problem

**Comment by ferllings** [comment]
I've added a logger to catch errors
Please try out v3.4.0 https://github.com/ThePacielloGroup/CCAe/releases/tag/v3.4.0
And send me your log folder: contact(AT)ferllings.me
- on macOS: ~/Library/Logs/{app name}/{process type}.log
- on Windows: %USERPROFILE%\AppData\Roaming\{app name}\logs\{process type}.log

**Comment by TLG95** [comment]
Hi,

Thank you for your time and the new build, it works.
Can I use this version to deploy it ?

[logs.zip](https://github.com/ThePacielloGroup/CCAe/files/12279877/logs.zip)

**Comment by ferllings** [comment]
If it works for you, yes.
