### ISSUE TITLE
CCA doesn't support Windows shortcut for moving windows between displays

### ISSUE THREAD

**Issue by PatUMW** [ThePacielloGroup/CCAe#305]
**Describe the bug**
The shortcut for moving windows between displays is Windows Key + Shift + Left or Right Key doesn't work with CCA.

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit
 - Version CCA 3.3.0

**To Reproduce**
1. Open CCA on PC with two displays and move CCA to the second display.
2. Start remote desktop session on another PC with only one display and connect to machine from point 1.
3. Use Windows Key + Shift + Left or Right Key to move CCA window from the second display to the first one. Fail. 

**Expected behavior**
CCA will be able to move via those Windows shortcuts.

**Comment by JOP-Temesis** [comment]
Regularly on Windows CCA is "lost" in the screen and unreachable. 
Installing this shortcut could allow CCA to force its positioning.

**Comment by ferllings** [comment]
It seems to works fine for me. Can you test with https://github.com/ThePacielloGroup/CCAe/suites/16582749397/artifacts/947367400 ?

**Comment by ferllings** [comment]
Added similar feature on Macos 7b953a64bac2a98474ef09f5ed741f2ad688162f

**Comment by handcoding** [comment]
> Added similar feature on Macos [7b953a6](https://github.com/ThePacielloGroup/CCAe/commit/7b953a64bac2a98474ef09f5ed741f2ad688162f)

@ferllings By the way, I believe that the above commit has caused a regression that has the effect of breaking some standard macOS keyboard shortcuts within all macOS applications (whenever the Color Contrast Analyzer is running). 

As of CCA 3.5.1, if the Color Contrast Analyzer is running, the standard macOS keyboard shortcuts `Cmd+Shift+Left` and `Cmd+Shift+Right` no longer appear to work in *any application*. 

[macOS has standard keyboard shortcuts for selecting text](https://support.apple.com/en-us/HT201236#:~:text=Shift–Command–Down%20Arrow%3A,end%20of%20the%20current%20line.), and among them are:
* `Cmd+Shift+Left` to select from the cursor position to the beginning of the line
* `Cmd+Shift+Right` to select from the cursor position to the end of the line

Here are steps to reproduce this issue on macOS if it may help:

1. Close the Color Contrast Analyzer if it may be running.
2. Open a new TextEdit document and paste in this text (or any other text):
  `The quick brown fox jumped over the lazy dog.`
3. Place the cursor just after the word “fox” and then press `Cmd+Shift+Left`. 
  * Result: ✔︎ The text from the cursor to the beginning of the line is selected.
4. Then open CCA 3.5.1 and repeat those steps:
   1.  Go back to the open TextEdit document from earlier (with the “quick brown fox” text).
   2. Place the cursor just after the word “fox” and then press `Cmd+Shift+Left`. 
* Expected result: The text from the cursor to the beginning of the line is selected.
* Actual result: Nothing happens.

Just for completeness: 
* I’m running the Color Contrast Analyzer on macOS 14.2.1.
* And I’ve also confirmed that this issue isn’t present when running CCA 3.4.2. for macOS.

**Comment by ferllings** [comment]
@handcoding Thanks Ashley. I'll probably make those shortcuts customizable

**Comment by handcoding** [comment]
Right on—that sounds good, @ferllings!
