### ISSUE TITLE
Citrix Virtual Desktop Compatability

### ISSUE THREAD

**Issue by jprasad2020** [ThePacielloGroup/CCAe#306]
Dear Team,

Greetings!!
I am looking for technical details for installation of CCA on Citrix Virtual Desktop.
Are there any technical challenges/limitations to use the CCA on Citrix Virtual Desktop.

If yes, then what are those and is there any solution/configuration/third party tool/add-on etc.. to fix those issues & use the CCA on Citrix Virtual desktop?

**Comment by jprasad2020** [comment]
Dear Team,
Can someone please help on this technical query?

**Comment by ferllings** [comment]
Sorry, I don't have any experience with Citrix.
You will have to try by yourself.
