### ISSUE TITLE
CCA with strange Behaviour

### ISSUE THREAD

**Issue by piep-piep-piep** [ThePacielloGroup/CCAe#308]
**Describe the bug**
We experienced some strange behaviour of the CCA exe.
We have seen that "Colour Contrast Analyser (CCA).exe" is dropping randomly named .tmp.exe files in the AppData\Local\Temp.
For example: C:\Users\<username>\AppData\Local\Temp\1f5643a6-56e6-4814-a9d0-75962964932b.tmp.exe

Those Files are not digitally signed and are looking suspicious.
Can you confirm the function and goal of these tmp.exe files?

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bits
 - Version: 3.1.2.0

**Expected behavior**
CCA should probably not drop .exe files in AppData\Local\Temp .

**Screenshots**
Not available.

**Additional context**
No additional context.

**Comment by ferllings** [comment]
This is a spawned process, by electron, for the eyedropper feature.
