### ISSUE TITLE
Auto Update Error to version 4.4.2

### ISSUE THREAD

**Issue by rpkoller** [ThePacielloGroup/CCAe#314]
**Describe the bug**
I am currently running CCA 3.3.0 on an Apple Silicon based computer. When i start the app and try to search for an update I run into an error. 
**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.6
 - Version CCA 3.3.0

**To Reproduce**
- Start the app and let the autoupdater run

**Expected behavior**
I would expect that the app is updated to 1.4.2

**Screenshots**
![Screenshot 2023-09-26 at 16 49 44](https://github.com/ThePacielloGroup/CCAe/assets/1665422/455602ab-216a-4669-8c32-aeebaacd7de0)

**Comment by ferllings** [comment]
Looks like the .zip hasn't been uploaded

**Comment by ferllings** [comment]
Fixed
