### ISSUE TITLE
The CCA downloads page does not provide a current Windows installer

### ISSUE THREAD

**Issue by mitchellevan** [ThePacielloGroup/CCAe#316]
**Describe the bug**
On the CCA downloads page, there are no links or instructions to obtain the current Windows installers, such as the .msi installer.

On the CCA downloads page, under the "Colour Contrast Analyzer (CCA)" heading, when I click "Windows" it immediately starts downloading the portable executable (not an installer):

https://github.com/ThePacielloGroup/CCAe/releases/download/v3.4.2/CCA-Portable-x64-3.4.2.exe

**Desktop (please complete the following information):**
 - OS: Windows 10
 - CCA Version: N/A. The problem is not in the CCA app itself, but in the CCA downloads page.

**To Reproduce**
1. Go to the CCA downloads page: https://www.tpgi.com/color-contrast-checker/
2. Look for instructions on how to obtain a Windows installer for the current version of CCA.
3. Under the "Colour Contrast Analyzer (CCA)" heading, click "Windows".

**Expected behavior**
The CCA downloads page should provide links or instructions to obtain the current Windows installers, such as the .msi installer.

On the CCA downloads page, under the "Colour Contrast Analyzer (CCA)" heading, when I click "Windows" it should not immediately start downloading the portable Windows executable without explanation.

**Screenshots**

![The "Windows" link under the "Colour Contrast Analyzer (CCA)" heading](https://github.com/ThePacielloGroup/CCAe/assets/3124805/9a38238e-9757-495f-8af9-b2df197dfa32)

**Comment by mitchellevan** [comment]
Workaround: https://github.com/ThePacielloGroup/CCAe/releases/

**Comment by ferllings** [comment]
I'll forward the request to the person in charge of the TPGi website.

**Comment by ferllings** [comment]
Fixed
