### ISSUE TITLE
Provider Certificate out of date with Version 3.5.1

### ISSUE THREAD

**Issue by LaHnk** [ThePacielloGroup/CCAe#334]
**Describe the bug**
The colour picker tool creates a temporary exe, which is signed with a provider certificate.
This certificate went out of date as of April 17th. In a corporate environment where normal users don't have admin rights to execute the exe, the execution can be allowed by whitelisting the provider. This workaround unfortunately doesn't work anymore without an up to date provider certificate. 

The main contributor to CCA TPGi Group has been contacted and is not able to provide a current certificate.
Does anyone have information on how to obtain an up to date certificate?

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise LTSC, 1809

**Comment by ferllings** [comment]
Hi,
We are testing a new method for signing certificates.
I'm going to release a new version next week.
But as a temporary solution, you can download the .exe here https://github.com/ThePacielloGroup/CCAe/actions/runs/8738505111

**Comment by LaHnk** [comment]
Hi, thanks for the reply! We'll wait for the new release including the new certificate.

**Comment by LaHnk** [comment]
Hi! When could we expect the new version since it hasn't been released yet? Thanks in advance!

**Comment by ferllings** [comment]
Released. Thanks for reminder

**Comment by KodeKangaroo** [comment]
Hi @ferllings, 
%localappdata%\temp\*.tmp.exe when trying to use "Colour picker" is still using the old certificate = still getting blocked by Applocker.  
Cheers.

**Comment by ferllings** [comment]
Fixed in 3.5.3
