### ISSUE TITLE
[Windows] Auto Update Error dialog (from 3.5.1 to 3.5.2)

### ISSUE THREAD

**Issue by PhilippeVay** [ThePacielloGroup/CCAe#338]
**Describe the bug**
After launching, using and closing CCAe 3.5.1 (UI in french), a system error dialog appears about an "`Auto Update Error:, Error spawn,` etc".
Second launch: same error dialog about `.../resources/elevate.exe ENOENT` (more details in the first screenshot below, sorry it won't let copy paste the text)
As with #335, `Install update` ("_Installer la mise à jour_") doesn't update to 3.5.2
While writing this bug report, CCAe changed the message on 3rd line (second screenshot): it has re-downloaded the update then offered to install this update via dialog in third screenshot. And then same error dialog.

So basically #335 but it's on Win 11 Pro, with an extra error dialog.  
I use a user account, no admin privilege and I very probably installed CCAe with this same account a month ago.

**Desktop (please complete the following information):**
 - OS: Windows 11 Professional 64 bits
 - Version 23H2, build 22631.3447
 - user account, not admin

**To Reproduce**
1. Have CCAe 3.5.1 installed on Win 11 Pro
2. Use it and close the program
3. An error dialog appears

**Expected behavior**
CCAe updates itself to version 3.5.2 without any error message, whether with an explicit close and restart or silently next time it's launched. _If_ admin privilege is required, it should still work with the usual Win process for that.

**Screenshots**
1. ![Error dialog. Auto Update Error](https://github.com/ThePacielloGroup/CCAe/assets/534395/d79d59c1-ca79-4720-bb36-09235353fd46)
5. ![Menu of CCAe Installer la mise à jour. Install update](https://github.com/ThePacielloGroup/CCAe/assets/534395/f4a9c1fd-e919-42d1-9fda-b6174e8be11b)
6. ![Dialog. Install updates. 3.5.2 has been downloaded. The application will be closed to install the update.](https://github.com/ThePacielloGroup/CCAe/assets/534395/61c46ab9-101b-49e9-9ee0-01d89dc0da2b)

**Comment by jritz1701** [comment]
Getting the same error when I close the CCA tool.  Tried a new installation with the same results.  In addition, I am also using Fusion 2024, combination of JAWS & Zoom Text which crashes as a result of this issue.

Operating System: Windows 11 Home

**Comment by KITA-info** [comment]
Any progress on this?  I am getting the same error.
