### ISSUE TITLE
Auto Update Error -> 3.5.3 unsigned

### ISSUE THREAD

**Issue by EqualEntry-Heather** [ThePacielloGroup/CCAe#339]
Error: New version 3.5.3 is not signed by the application owner: publiserNames: TPGi Interactive, LLC

 - OS: Windows 11 Pro
 - Version 23H2
 - Build 22631.3447

**Repro steps
Launch CCA
open menu Colour Contrast Analyser (CCA)

**Expected behavior**
Menu to show that the application is up to date

**Screenshots**
![image](https://github.com/ThePacielloGroup/CCAe/assets/43451139/b95439a9-5059-4e58-9f3c-11a31666c5be)

**Additional context**
Error dialog appears behind the CCA making it a bit harder to deal with.

**Comment by ferllings** [comment]
mmm... the new signing process may have changed the publisherName.
Thanks for the report

**Comment by patrickhlauke** [comment]
Confirming that it's happening here as well...

**Comment by ferllings** [comment]
I've been trying few things, but I'm afraid the only solution is to manually reinstall.
