### ISSUE TITLE
The "Picker background" and "Picker foreground" texts in the application settings should be swapped

### ISSUE THREAD

**Issue by Korb** [ThePacielloGroup/CCAe#348]
**Describe the bug**
The shortcuts installed in the application settings are swapped: the key for "Picker background" activates the eyedropper for Picker foreground, and the key for "Picker foreground" activates the eyedropper for Picker background.

In addition, the color order in the main application window and in the settings should match. If "Foreground color" comes first in the main menu, and "Background color" comes second, then the order in the settings should be the same. It is like this now, only the texts do not match.

**Desktop (please complete the following information):**
- OS: Microsoft Windows 10.0.19045.4717
- Version CCA-Portable-x64-3.5.3

**To Reproduce**
1. Launch the application, go to settings, and assign "Picker background" and "Picker foreground".
2. Close settings, and make sure that the combination assigned to "Picker background" changes the color of "Foreground color", and the key for "Picker foreground" changes "Background color".

**Expected behavior**
"Picker foreground" → "Foreground color"
"Picker background" → "Background color"

**Comment by Korb** [comment]
> @ferllings ferllings closed this as completed in 38b4793 Aug 19, 2024

When is a release with this fix expected?

**Comment by ferllings** [comment]
@Korb I'm waiting for another contributer.
