### ISSUE TITLE
with AA and AAA results turned on, text overflows/is cut off

### ISSUE THREAD

**Issue by patrickhlauke** [ThePacielloGroup/CCAe#41]
> ![cca-textcutoff](https://user-images.githubusercontent.com/895831/45036411-5a170680-b054-11e8-9914-1f816c4c34ef.PNG)
(note 1.4.3, the AAA result is cut off - and without scrollbars or window resizing, can't be reached/seen)

**Comment by ferllings** [comment]
The AAA option is simply disabled : "Options" > "Display Level AAA"

**Comment by patrickhlauke** [comment]
sorry, managed to confuse myself there. i was somehow expecting that red Fail text to be about AAA (and then thinking that's cut off on the right).

raises a different question then: the "Pass AA" text makes no sense as it's the SC as a whole that's AA. incoming PR...
