### ISSUE TITLE
Omit "View > Open Developer Tools" from release builds

### ISSUE THREAD

**Issue by patrickhlauke** [ThePacielloGroup/CCAe#53]
From skype, paraphrased:

> wondering if for the final release we should disable the "View > Open Developer Tools" menu option
> hoping there's an easy way to have that option only show if you're, say, `npm run start`-ing this locally, but not when it's a packaged executable
> this would allow devtools for development work, but when it comes time to package a release you won't have to explicitly go into code / mess around to disable it (as manual stuff like that always gets forgotten)
> not so much about keeping our code secret...the github repo is public, there's no shame/problem in having devtools there. but it may confuse "regular" users (who may think this, like "Colour deficiencies", is another option/tool/window for the app, rather than a "look under the hood of the app" option)

**Comment by ferllings** [comment]
Fixed in d3d5d5a4746123cee02670734ebdb997d83bddbe

**Comment by patrickhlauke** [comment]
wow, perfect. will try it out in a minute :)
