### ISSUE TITLE
Ability to switch between HEX/RGB(a)/HSL(a) in the large foreground/background textboxes and remember that format setting

### ISSUE THREAD

**Issue by patrickhlauke** [ThePacielloGroup/CCAe#63]
It would be a nice added feature if a user could click the "HEX" or whatever, and it automagically, cycled between then displaying the same thing in rgba and hsla.

also, that it tries to retain what the currently shown/selected format is. currently, if i enter a value in rgba, and then use sliders to further tweak it, it reverts back to HEX.

> ![ccae-format](https://user-images.githubusercontent.com/895831/46278129-2f3da680-c55d-11e8-8aba-560ceaccae07.jpg)

**Comment by ferllings** [comment]
Good idea. Relates to #57

**Comment by robsonsobral** [comment]
It's much easier to find a contrasting color on HSL than RGB. "Oh, shit! The color is too light! Let's pull this slider and... Good!"

**Comment by ferllings** [comment]
@robsonsobral yes, this relates to #56
