### ISSUE TITLE
Downloaded installer from GitHub triggers Windows Defender SmartScreen

### ISSUE THREAD

**Issue by patrickhlauke** [ThePacielloGroup/CCAe#66]
When the installer for CCA is downloaded from GitHub, running the installer causes the scary looking Windows Defender SmartScreen dialog to appear.

> ![ccae-github-install](https://user-images.githubusercontent.com/895831/46539104-91740f80-c8ad-11e8-8fc6-3b88022fd5d3.PNG)

While the installer is digitally signed, we'd likely require an an Extended Validation (EV) certificate to prevent this from happening.

**Comment by patrickhlauke** [comment]
This doesn't seem to happen anymore. Closing.

**Comment by patrickhlauke** [comment]
urgh, what am i saying, it's still happening. just that the warning looked different to me at first glance. as you were, still an issue

**Comment by RRC-TX-IS** [comment]
Is there an ETC on when this will be resolved?

**Comment by ferllings** [comment]
Should be fixed with current signing certificate

**Comment by patrickhlauke** [comment]
Confirming that I didn't get the scary warning this time around
