### ISSUE TITLE
The eyedropper doesn't seem to work on MAC

### ISSUE THREAD

**Issue by DavidMacDonald** [ThePacielloGroup/CCAe#74]
I've been playing with the new contrast analyser for about 30 minutes and have yet to get a sample of a colour with the eyedropper. 

Am I missing something?

Using CHROME latest, MacOS latest.

**Comment by patrickhlauke** [comment]
you've successfully, or unsuccesfully? not quite clear what you mean. can you provide some more detail about what your issue is?

**Comment by DavidMacDonald** [comment]
I've run it on a second MacBook and its running OK there.... so it seems like an installation issue.
