### ISSUE TITLE
Use of Colour 3:1 criteria 

### ISSUE THREAD

**Issue by davvwar** [ThePacielloGroup/CCAe#77]
I'll sometimes use the CCA to discuss issues with Use of Colour (1.4.1). It has a technique that links can *only* be communicated by colour if they pass a 3:1 requirement. 

The CCA better supports this due to 3:1 being the ratio for 1.4.11. It would be nice if the above could be formally added, though -- even if it was an optional add-on configurable in the settings. 

Can understand why it's not currently there. It's a technique and not a normative part of the success criteria. It would nonetheless be a nice addition.

**Comment by ferllings** [comment]
Sorry, I'm trying to keep the interface as minimal as possible.
