### ISSUE TITLE
How to contribute localization/translation

### ISSUE THREAD

**Issue by MakotoUeki** [ThePacielloGroup/CCAe#79]
Congratulations on the new version release!

I'm wondering if there is an established way of translating UI into various languages. I'd like to contribute to Japanese translation as I did it for the “CCA Classic”.

**Comment by patrickhlauke** [comment]
ohaio makoto :)

currently, CCAe isn't quite set up for internationalisation/translation just yet. there are some aspects we need to investigate and plan for:

- do electron apps pick up the user's operating system locale (e.g. to check which language the OS is set to)?
- splitting out all strings into separate language/translation files (so no actual strings are hard-coded into the html/js, but it's all handled by grabbing strings from a language file
- providing options/settings for users to change the language (so they can set it to something other than the OS locale if they wish)

we've admittedly not planned the above (with exception of some high-level "settings/saving preferences" idea)...so i don't think it'll happen anytime soon. but it's certainly something we're hoping to have in a future version.

**Comment by MakotoUeki** [comment]
Patrick, thanks for sharing. I understood the situation. CCA is commonly used also in Japan. I'm looking forward to the future version.

Cheers!
