### ISSUE TITLE
How to download/install “CCA Classic”

### ISSUE THREAD

**Issue by MakotoUeki** [ThePacielloGroup/CCAe#80]
Could you provide the instructions on how to download/install “CCA Classic”?

I'd like to keep introducing "CCA Classic" for the time being because the Japanese version of CCAe is not available at this moment.

Many people who want to use CCA don't know anything about GitHub. Even if they get to the repositories, they will get lost as they have no idea what to do there.
https://github.com/ThePacielloGroup/CCA-Win
https://github.com/ThePacielloGroup/CCA-OSX

**Comment by patrickhlauke** [comment]
Added a "Download" bit in the readme for each repo

**Comment by MakotoUeki** [comment]
Thanks, Patrick!
