### ISSUE TITLE
Color picker not working Windows

### ISSUE THREAD

**Issue by selphiras** [ThePacielloGroup/CCAe#82]
I just downloaded the latest version because I accidentally deleted the old one. I can't get the color picker to work. When I click on it, it just displays a rectangle of whatever is on the screen right where the color picker is. In the screen shot, you can see part of this message, which I was writing when I got the screen shot--the white area with text.

If I move it around, that rectangle of text/colors/whathaveyou goes to, and doesn't allow me to actually pick any specific color. (Well, sometimes it does register, but since I can't see what I'm click on below this rectangle, I can't really pick anything.)
![2018-11-01 10_47_43-new issue thepaciellogroup_ccae](https://user-images.githubusercontent.com/39196723/47862686-b338b780-ddc3-11e8-92e4-9b2a671625b4.png)

**Comment by ferllings** [comment]
Could you try to re-install the previous version?
To confirm that this is something related to our latest changes.

**Comment by mezapata** [comment]
I have this issue as well with 1.0.0. 
I have an older version (2.5.0.0), and it does not have this issue.

**Comment by mezapata** [comment]
With 1.1.1, this issue manifests itself a bit differently (as shown in the screenshot below).  The nature  of this issue (being unable to see exactly what you're trying to pick) is still the same.
![CCA111_issue](https://user-images.githubusercontent.com/27693680/56312721-6dc03a80-6116-11e9-86ac-dbd7ea87d7ca.png)
I have an older version of CCA (2.5.0.0), and it does not have this issue.

**Comment by patrickhlauke** [comment]
just noting that the "older" version of CCA is essentially a completely separate (and now abandoned) codebase, using different technology altogether, so unrelated to the new CCA.

what version of Windows? and do you have any specific additional assistive technology software running, or some specific settings/themes enabled in Windows? (in essence the problem seems to be that what should be a transparent window is not transparent)

**Comment by mezapata** [comment]
I am using Windows 7 Enterprise, Service Pack 1; with no assistive technology running and no custom settings nor themes enabled (other those imposed by my company's IT dept, which I'm not privy to.).

**Comment by patrickhlauke** [comment]
Most likely an issue with Windows 7 then. We can probably try to see if anything in https://github.com/electron/electron/issues/2170 can help, but note that Win7 is now a rather old system which we're likely not going to be able to fully support going forward (considering it's now in its last year before extended support by MS is officially ended - and mainstream support ended in 2015)

**Comment by MarcusMorba** [comment]
I just tried the portable latest and have a similar issue on Windows 7. It does not pick up any color value.

**Comment by semelle1161** [comment]
I just downloaded the latest version 3.5.5. The color picker does not move. I am unable to drag and drop the color picker from the Forground and Background Colour. Help!
