### ISSUE TITLE
Colour blindness simulation on Mac not working?

### ISSUE THREAD

**Issue by andreasbossard** [ThePacielloGroup/CCAe#86]
When I open "view --> color blindness simulation" I get presented with this screen 
![image](https://user-images.githubusercontent.com/502464/51033452-abf01000-15a3-11e9-8cf3-c10f0659d2d8.png)

Is this really correct? In the past I tried it on Windows and there you could really simulate part of the screen how it would look like for different types of color blindness.

**Comment by ferllings** [comment]
Yes, the screen is correct.
The old window simulator view hasn't been implemented in the new CCA.

**Comment by andreasbossard** [comment]
@ferllings but this means that the menu item "view --> color blindness simulation" should be removed, or is wrongly named, or not?

**Comment by patrickhlauke** [comment]
if you choose actual colours in the main window, this will show you their simulated appearance for different colour vision deficiencies. so it's working as intended.
