### ISSUE TITLE
Linux support (AppImage)

### ISSUE THREAD

**Issue by Xaviju** [ThePacielloGroup/CCAe#87]
Linux users would love to use this tool but on 1.0 there is no linux build available.

Targeting all Linux desktops should be easy using Electron -> AppImage. 
Electron docs on how to build Appimages here: https://www.electron.build/configuration/linux

**Comment by ferllings** [comment]
I would love to have a linux version too, but the native dependency we use to track the mouse for the picker doesn't work on Linux.
[osx-mouse|https://github.com/kapetan/osx-mouse] and [win-mouse|https://github.com/kapetan/win-mouse]

I'm looking for alternatives.

**Comment by bzg** [comment]
Hi, I've found a few `npm` packages to track the pointer position under the category [pointer tracking](https://www.npmjs.com/search?q=keywords%3A%22pointer%20tracking%22).

The most relevant seems to be [popmoption](https://popmotion.io/learn/get-started/).

It would indeed be very nice to add support for running CCAe under GNU/Linux!

**Comment by ferllings** [comment]
Well, the good news is that CCAe no longer use JS for the picker. It uses native little external apps.
So we "simply" need an external picker tool on Linux.
We can either build one or use an existing tools like [SCROT](https://github.com/resurrecting-open-source-projects/scrot)

**Comment by bzg** [comment]
Great news indeed, and thanks in advance for your efforts, they'll have an impact where I work!

**Comment by ferllings** [comment]
Thanks for reminding me about this ticket: Linux support is definitely something I want to achieve.

**Comment by bzg** [comment]
Hi @ferllings - I hope the Covid crisis did not hurt you.  Is this something you still want to do?  Thanks and good luck!

**Comment by ferllings** [comment]
Absolutely, but I'm currently facing some reliability and security problems with the picker, and I'm trying to solve them before.

**Comment by bzg** [comment]
Hi, I hope things are fine on your end - just checking if you had a chance to look at this?

**Comment by ferllings** [comment]
I'm afraid not. No much time to work on CCA these days.

**Comment by bzg** [comment]
Okay, no problem and thanks for your feedback.

**Comment by Xaviju** [comment]
Great news!

Tested it on Linux and works fine!
Thanks a lot for your work @ferllings

**Comment by ferllings** [comment]
@Xaviju , I was only able to test under ubuntu. What distro do you use?

**Comment by Xaviju** [comment]
> @Xaviju , I was only able to test under ubuntu. What distro do you use?
> 
> For those who want to test, you can find the build previews here: https://github.com/ThePacielloGroup/CCAe/actions/runs/6313973127

Tested on EndeavourOS (Linux 6.5.4-arch2-1) - Gnome desktop
