### ISSUE TITLE
Can’t paste hex code

### ISSUE THREAD

**Issue by thomasedwards** [ThePacielloGroup/CCAe#88]
1. Selected `010101` in a text editor
2. Press _Edit_ > _Copy_ from the menu
3. Looked for _Paste_ option in _Edit_ menu, not there
4. Used standard keyboard shortcut, `Cmd`+`V`, nothing happens

**Comment by patrickhlauke** [comment]
fun times...seems electron/mac doesn't allow copy/paste by default (works out of the box on windows, for what it's worth). https://www.google.com/search?q=electron+mac+copy

we'll have to implement custom clipboard API behavior for this, or use the "add the options to the edit menu of the application" trick...

**Comment by ferllings** [comment]
As a temporary solution, you can use "past" from the contextual menu.
