### ISSUE TITLE
App file size is large

### ISSUE THREAD

**Issue by thomasedwards** [ThePacielloGroup/CCAe#89]
The previous app for macOS was 12MB. 1.0 of this new app is 125MB. Many people around the world don’t have fast internet. 125MB can take 30 minutes to download in many locations, previously it would have taken 3 minutes. Anything than can be done to reduce the file size would make the app more accessible.

I understand that this might be due to the use of the framework to build the app, but if it is possible it can make a big difference to a lot of people.

**Comment by patrickhlauke** [comment]
that's the current payload for electron applications. nothing we can do about it at the moment, i'm afraid.
