### ISSUE TITLE
Enterprise version that installs into Program Files request

### ISSUE THREAD

**Issue by Drekko** [ThePacielloGroup/CCAe#93]
Hello
I e-mailed your support about an issue we have with the latest version of CCA that was re-built:
https://developer.paciellogroup.com/resources/contrastanalyser/
It installs into the users profile and we find this is unreliable with our environments security policies.
It will not install correctly into the user's profile. The previous version which installed into Program Files installed without any issues.

I have had to roll back our staff who use this application to the previous version meantime. 
I was told by your support that you could probably change that and to post a request here
Id would very much appreciate if you could do this

**Comment by ddlowe** [comment]
Yes, an enterprise version which installs silently would be good. An msi version of this would be even better!

**Comment by ferllings** [comment]
Yes, I'll try to build a msi version. That should be a problem with [electron-builder](https://github.com/electron-userland/electron-builder)

**Comment by ddlowe** [comment]
The msi would be great, but an enterprise, per-device installation would be even better! If it's a case of just moving  file installation locations, I can do this for our own copy! (or maybe there's more to it than that ...?)

**Comment by ferllings** [comment]
Fixed in 34d8000586aa4ae31b2f406bb9ad84bf93da19c4
