### ISSUE TITLE
CCA and multiple monitors: relaunching places CCA on "phantom" monitor

### ISSUE THREAD

**Issue by kensgists** [ThePacielloGroup/CCAe#94]
I typically use CCA on a laptop attached to external monitors -- extended desktops -- often opening and placing the CCA app on one of these externals.

If I quit CAA, when I open it again, it will remember where it was placed. However, if I disconnect my laptop from the external monitors -- to go work elsewhere where I don't have an external monitor -- when I launch CCA again, it "remembers" where it was last placed and launches on that phantom monitor.

**Comment by ferllings** [comment]
I can't reproduce. Could you give me more details?

What OS?
CCAe Version?

**Comment by mattbrough** [comment]
I've observed this issue in CCA classic, but it appears resolved for me in CCAe.

(Windows 10 64-bit, CCAe v1.1.1)

**Comment by kensgists** [comment]
Thanks. You're correct. This is no longer an issue in the Electron-based CCA. 

This can be closed/cancelled.

**Comment by ferllings** [comment]
Thanks !
