### ISSUE TITLE
MSI installed version has broken/missing icon

### ISSUE THREAD

**Issue by patrickhlauke** [ThePacielloGroup/CCAe#98]
Version: v1.1.0
OS: Windows 10

Installing the MSI version (regardless of just for the current user, or all users) results in broken app icon (on desktop and in the taskbar)

![cca-bug4](https://user-images.githubusercontent.com/895831/55671276-75662080-5886-11e9-949a-25e69cc1d2ce.PNG)

**Comment by patrickhlauke** [comment]
still an issue in 1.2.0

**Comment by adamabbate-ais** [comment]
Still an issue in 3.1.3 unfortunately too.

**Comment by ferllings** [comment]
I still can't reproduce the issue.

The msi installer, with fresh installed Windows 10:
![Screenshot of the CCA installed shortcut, correctly displaying the icon](https://user-images.githubusercontent.com/2118130/124716814-c8ffc280-df04-11eb-841d-fde2605d3348.png)

**Comment by patrickhlauke** [comment]
confirming that it works fine for me now, both for MSI and the .exe installer
