### ISSUE TITLE
Javascript error on launch of CCA from MSI install

### ISSUE THREAD

**Issue by TGBXX** [ThePacielloGroup/CCAe#99]
CCA 1.1.0 was installed through the MSI. But when launched displays a Javascript error.
![Capture8](https://user-images.githubusercontent.com/28941324/55696263-871f0380-59ff-11e9-8504-891959737030.PNG)
After clearing this, it then _seems_ to launch okay.
![Capture10](https://user-images.githubusercontent.com/28941324/55696468-699e6980-5a00-11e9-9779-af0f3c8c7f6a.PNG)
In the AppData Temp directory at the path mentioned in the Javascript error:
![Capture9](https://user-images.githubusercontent.com/28941324/55696386-0d3b4a00-5a00-11e9-9ecb-100e658475e0.PNG)
This error occurs on every launch.

**Comment by ferllings** [comment]
What OS do you use? 32b or 64b?

Could you also try to launch the color picker?

I believe one of the native libs hasn't been properly built.
